+incdir+${CL_ROOT}/design/hls_accel/bnn
${CL_ROOT}/design/hls_accel/bnn/top_bin_conv_fixed_buffer_V_0.v
${CL_ROOT}/design/hls_accel/bnn/top_bin_conv.v
${CL_ROOT}/design/hls_accel/bnn/top_bin_dense.v
${CL_ROOT}/design/hls_accel/bnn/top_control_s_axi.v
${CL_ROOT}/design/hls_accel/bnn/top_conv_word.v
${CL_ROOT}/design/hls_accel/bnn/top_dmem_V_1_1_ram.v
${CL_ROOT}/design/hls_accel/bnn/top_dmem_V_1_1.v
${CL_ROOT}/design/hls_accel/bnn/top_fp_conv.v
${CL_ROOT}/design/hls_accel/bnn/top_gmem_m_axi.v
${CL_ROOT}/design/hls_accel/bnn/top_kh_mem_V_ram.v
${CL_ROOT}/design/hls_accel/bnn/top_kh_mem_V.v
${CL_ROOT}/design/hls_accel/bnn/top_mac_muladd_10s_5ns_10ns_10_4_1.v
${CL_ROOT}/design/hls_accel/bnn/top_mac_muladd_20s_16s_28s_34_4_1.v
${CL_ROOT}/design/hls_accel/bnn/top_mul_10s_5ns_10_1_1.v
${CL_ROOT}/design/hls_accel/bnn/top_mul_mul_12s_5ns_12_4_1.v
${CL_ROOT}/design/hls_accel/bnn/top_mux_164_64_1_1.v
${CL_ROOT}/design/hls_accel/bnn/top_mux_325_20_1_1.v
${CL_ROOT}/design/hls_accel/bnn/top_mux_83_2_1_1.v
${CL_ROOT}/design/hls_accel/bnn/top.v
${CL_ROOT}/design/hls_accel/bnn/top_wt_mem_V_1_ram.v
${CL_ROOT}/design/hls_accel/bnn/top_wt_mem_V_1.v
