+incdir+${CL_ROOT}/design/hls_accel/spam_filter
${CL_ROOT}/design/hls_accel/spam_filter/SgdLR_aesl_mux_load_4_1125_x_i8P0A_i64_i64.v
${CL_ROOT}/design/hls_accel/spam_filter/SgdLR_compute_gradient_V_0.v
${CL_ROOT}/design/hls_accel/spam_filter/SgdLR_compute_lut_V.v
${CL_ROOT}/design/hls_accel/spam_filter/SgdLR_compute.v
${CL_ROOT}/design/hls_accel/spam_filter/SgdLR_control_s_axi.v
${CL_ROOT}/design/hls_accel/spam_filter/SgdLR_dataflow_in_loop_TRAINING_INST_entry6.v
${CL_ROOT}/design/hls_accel/spam_filter/SgdLR_dataflow_in_loop_TRAINING_INST_training_instance_V_0_memcore.v
${CL_ROOT}/design/hls_accel/spam_filter/SgdLR_dataflow_in_loop_TRAINING_INST_training_instance_V_0.v
${CL_ROOT}/design/hls_accel/spam_filter/SgdLR_dataflow_in_loop_TRAINING_INST.v
${CL_ROOT}/design/hls_accel/spam_filter/SgdLR_dataflow_parent_loop_proc.v
${CL_ROOT}/design/hls_accel/spam_filter/SgdLR_fifo_w13_d2_S.v
${CL_ROOT}/design/hls_accel/spam_filter/SgdLR_fifo_w64_d2_S.v
${CL_ROOT}/design/hls_accel/spam_filter/SgdLR_fifo_w8_d2_S.v
${CL_ROOT}/design/hls_accel/spam_filter/SgdLR_gmem_m_axi.v
${CL_ROOT}/design/hls_accel/spam_filter/SgdLR_label_local_V_0.v
${CL_ROOT}/design/hls_accel/spam_filter/SgdLR_mul_32s_16s_44_2_1.v
${CL_ROOT}/design/hls_accel/spam_filter/SgdLR_mul_32s_32s_51_2_1.v
${CL_ROOT}/design/hls_accel/spam_filter/SgdLR_mul_mul_28s_16s_44_4_1.v
${CL_ROOT}/design/hls_accel/spam_filter/SgdLR_READ_TRAINING_DATA_proc.v
${CL_ROOT}/design/hls_accel/spam_filter/SgdLR_theta_local_V_0.v
${CL_ROOT}/design/hls_accel/spam_filter/SgdLR.v
