// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module top_bin_dense (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        layer_type,
        d_i_idx,
        d_o_idx,
        o_index,
        n_inputs,
        n_outputs,
        dmem_V_1_1_address0,
        dmem_V_1_1_ce0,
        dmem_V_1_1_we0,
        dmem_V_1_1_d0,
        dmem_V_1_1_q0,
        dmem_V_1_0_address0,
        dmem_V_1_0_ce0,
        dmem_V_1_0_we0,
        dmem_V_1_0_d0,
        dmem_V_1_0_q0,
        dmem_V_0_1_address0,
        dmem_V_0_1_ce0,
        dmem_V_0_1_we0,
        dmem_V_0_1_d0,
        dmem_V_0_1_q0,
        dmem_V_0_0_address0,
        dmem_V_0_0_ce0,
        dmem_V_0_0_we0,
        dmem_V_0_0_d0,
        dmem_V_0_0_q0,
        wt_mem_V_0_address0,
        wt_mem_V_0_ce0,
        wt_mem_V_0_q0,
        wt_mem_V_1_address0,
        wt_mem_V_1_ce0,
        wt_mem_V_1_q0,
        kh_mem_V_address0,
        kh_mem_V_ce0,
        kh_mem_V_q0,
        kh_mem_V_address1,
        kh_mem_V_ce1,
        kh_mem_V_q1
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_pp0_stage0 = 10'd8;
parameter    ap_ST_fsm_state10 = 10'd16;
parameter    ap_ST_fsm_state11 = 10'd32;
parameter    ap_ST_fsm_state12 = 10'd64;
parameter    ap_ST_fsm_state13 = 10'd128;
parameter    ap_ST_fsm_state14 = 10'd256;
parameter    ap_ST_fsm_state15 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [1:0] layer_type;
input  [0:0] d_i_idx;
input  [0:0] d_o_idx;
input  [15:0] o_index;
input  [15:0] n_inputs;
input  [15:0] n_outputs;
output  [9:0] dmem_V_1_1_address0;
output   dmem_V_1_1_ce0;
output   dmem_V_1_1_we0;
output  [63:0] dmem_V_1_1_d0;
input  [63:0] dmem_V_1_1_q0;
output  [9:0] dmem_V_1_0_address0;
output   dmem_V_1_0_ce0;
output   dmem_V_1_0_we0;
output  [63:0] dmem_V_1_0_d0;
input  [63:0] dmem_V_1_0_q0;
output  [9:0] dmem_V_0_1_address0;
output   dmem_V_0_1_ce0;
output   dmem_V_0_1_we0;
output  [63:0] dmem_V_0_1_d0;
input  [63:0] dmem_V_0_1_q0;
output  [9:0] dmem_V_0_0_address0;
output   dmem_V_0_0_ce0;
output   dmem_V_0_0_we0;
output  [63:0] dmem_V_0_0_d0;
input  [63:0] dmem_V_0_0_q0;
output  [11:0] wt_mem_V_0_address0;
output   wt_mem_V_0_ce0;
input  [63:0] wt_mem_V_0_q0;
output  [11:0] wt_mem_V_1_address0;
output   wt_mem_V_1_ce0;
input  [63:0] wt_mem_V_1_q0;
output  [5:0] kh_mem_V_address0;
output   kh_mem_V_ce0;
input  [63:0] kh_mem_V_q0;
output  [5:0] kh_mem_V_address1;
output   kh_mem_V_ce1;
input  [63:0] kh_mem_V_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[9:0] dmem_V_1_1_address0;
reg dmem_V_1_1_ce0;
reg dmem_V_1_1_we0;
reg[9:0] dmem_V_1_0_address0;
reg dmem_V_1_0_ce0;
reg dmem_V_1_0_we0;
reg[63:0] dmem_V_1_0_d0;
reg[9:0] dmem_V_0_1_address0;
reg dmem_V_0_1_ce0;
reg dmem_V_0_1_we0;
reg[9:0] dmem_V_0_0_address0;
reg dmem_V_0_0_ce0;
reg dmem_V_0_0_we0;
reg[63:0] dmem_V_0_0_d0;
reg wt_mem_V_0_ce0;
reg wt_mem_V_1_ce0;
reg kh_mem_V_ce0;
reg kh_mem_V_ce1;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [15:0] i_V_8_reg_517;
reg   [15:0] sum_V_reg_528;
wire   [0:0] d_o_idx_read_read_fu_314_p2;
wire   [16:0] lhs_fu_540_p1;
reg   [16:0] lhs_reg_4441;
wire   [18:0] zext_ln613_fu_544_p1;
reg   [18:0] zext_ln613_reg_4446;
wire   [0:0] cmp_i_i426_fu_548_p2;
reg   [0:0] cmp_i_i426_reg_4451;
wire   [5:0] trunc_ln1346_fu_554_p1;
reg   [5:0] trunc_ln1346_reg_4459;
wire   [6:0] trunc_ln1346_1_fu_558_p1;
reg   [6:0] trunc_ln1346_1_reg_4464;
wire   [0:0] xor_ln689_fu_562_p2;
reg   [0:0] xor_ln689_reg_4469;
wire   [15:0] o_V_fu_568_p2;
reg   [15:0] o_V_reg_4474;
wire    ap_CS_fsm_state2;
wire   [18:0] add_ln605_fu_574_p2;
reg   [18:0] add_ln605_reg_4479;
reg   [0:0] tmp_reg_4487;
wire   [0:0] icmp_ln605_fu_579_p2;
reg   [9:0] dmem_V_0_0_addr_reg_4494;
reg   [9:0] dmem_V_0_1_addr_reg_4499;
reg   [9:0] dmem_V_1_0_addr_reg_4504;
reg   [9:0] dmem_V_1_1_addr_reg_4509;
wire   [7:0] prediction_V_fu_643_p1;
reg   [7:0] prediction_V_reg_4517;
wire    ap_CS_fsm_state3;
wire   [5:0] o_offset_fu_651_p2;
reg   [5:0] o_offset_reg_4522;
wire   [63:0] o_word_V_4_fu_690_p3;
reg   [63:0] o_word_V_4_reg_4527;
wire   [0:0] icmp_ln878_fu_698_p2;
reg   [0:0] icmp_ln878_reg_4534;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state4_pp0_stage0_iter0;
wire    ap_block_state5_pp0_stage0_iter1;
wire    ap_block_state6_pp0_stage0_iter2;
wire    ap_block_state7_pp0_stage0_iter3;
wire    ap_block_state8_pp0_stage0_iter4;
wire    ap_block_state9_pp0_stage0_iter5;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln878_reg_4534_pp0_iter1_reg;
reg   [0:0] icmp_ln878_reg_4534_pp0_iter2_reg;
reg   [0:0] icmp_ln878_reg_4534_pp0_iter3_reg;
reg   [0:0] icmp_ln878_reg_4534_pp0_iter4_reg;
wire   [15:0] i_V_fu_703_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [63:0] xor_ln1350_fu_760_p2;
reg   [63:0] xor_ln1350_reg_4573;
reg   [0:0] tmp_851_reg_4578;
reg   [0:0] tmp_852_reg_4583;
reg   [0:0] tmp_853_reg_4588;
reg   [0:0] tmp_854_reg_4593;
reg   [0:0] tmp_855_reg_4598;
reg   [0:0] tmp_856_reg_4603;
reg   [0:0] tmp_857_reg_4608;
reg   [0:0] tmp_858_reg_4613;
reg   [0:0] tmp_859_reg_4618;
reg   [0:0] tmp_860_reg_4623;
reg   [0:0] tmp_861_reg_4628;
reg   [0:0] tmp_862_reg_4633;
reg   [0:0] tmp_863_reg_4638;
reg   [0:0] tmp_864_reg_4643;
reg   [0:0] tmp_865_reg_4648;
reg   [0:0] tmp_866_reg_4653;
reg   [0:0] tmp_867_reg_4658;
reg   [0:0] tmp_868_reg_4663;
reg   [0:0] tmp_869_reg_4668;
reg   [0:0] tmp_870_reg_4673;
reg   [0:0] tmp_871_reg_4678;
reg   [0:0] tmp_872_reg_4683;
reg   [0:0] tmp_873_reg_4688;
reg   [0:0] tmp_874_reg_4693;
reg   [0:0] tmp_875_reg_4698;
reg   [0:0] tmp_876_reg_4703;
reg   [0:0] tmp_877_reg_4708;
reg   [0:0] tmp_878_reg_4713;
reg   [0:0] tmp_879_reg_4718;
reg   [0:0] tmp_880_reg_4723;
reg   [0:0] tmp_881_reg_4728;
reg   [0:0] tmp_882_reg_4733;
wire   [63:0] xor_ln1350_1_fu_1029_p2;
reg   [63:0] xor_ln1350_1_reg_4738;
reg   [0:0] tmp_883_reg_4743;
reg   [0:0] tmp_884_reg_4748;
reg   [0:0] tmp_885_reg_4753;
reg   [0:0] tmp_886_reg_4758;
reg   [0:0] tmp_887_reg_4763;
reg   [0:0] tmp_888_reg_4768;
reg   [0:0] tmp_889_reg_4773;
reg   [0:0] tmp_890_reg_4778;
reg   [0:0] tmp_891_reg_4783;
reg   [0:0] tmp_892_reg_4788;
reg   [0:0] tmp_893_reg_4793;
reg   [0:0] tmp_894_reg_4798;
reg   [0:0] tmp_895_reg_4803;
reg   [0:0] tmp_896_reg_4808;
reg   [0:0] tmp_897_reg_4813;
reg   [0:0] tmp_898_reg_4818;
reg   [0:0] tmp_899_reg_4823;
reg   [0:0] tmp_900_reg_4828;
reg   [0:0] tmp_901_reg_4833;
reg   [0:0] tmp_902_reg_4838;
reg   [0:0] tmp_903_reg_4843;
reg   [0:0] tmp_904_reg_4848;
reg   [0:0] tmp_905_reg_4853;
reg   [0:0] tmp_906_reg_4858;
reg   [0:0] tmp_907_reg_4863;
reg   [0:0] tmp_908_reg_4868;
reg   [0:0] tmp_909_reg_4873;
reg   [0:0] tmp_910_reg_4878;
reg   [0:0] tmp_911_reg_4883;
reg   [0:0] tmp_912_reg_4888;
reg   [0:0] tmp_913_reg_4893;
reg   [0:0] tmp_914_reg_4898;
wire   [1:0] tmp_5_fu_1408_p4;
reg   [1:0] tmp_5_reg_4903;
wire   [1:0] tmp_6_fu_1418_p4;
reg   [1:0] tmp_6_reg_4909;
wire   [1:0] tmp_7_fu_1428_p4;
reg   [1:0] tmp_7_reg_4915;
wire   [1:0] tmp_8_fu_1438_p4;
reg   [1:0] tmp_8_reg_4922;
wire   [1:0] tmp_9_fu_1448_p4;
reg   [1:0] tmp_9_reg_4929;
wire   [1:0] tmp_10_fu_1458_p4;
reg   [1:0] tmp_10_reg_4936;
wire   [1:0] tmp_11_fu_1468_p4;
reg   [1:0] tmp_11_reg_4943;
wire   [1:0] tmp_12_fu_1478_p4;
reg   [1:0] tmp_12_reg_4951;
wire   [1:0] tmp_13_fu_1488_p4;
reg   [1:0] tmp_13_reg_4959;
wire   [1:0] tmp_14_fu_1498_p4;
reg   [1:0] tmp_14_reg_4967;
wire   [1:0] tmp_15_fu_1508_p4;
reg   [1:0] tmp_15_reg_4975;
wire   [1:0] tmp_16_fu_1518_p4;
reg   [1:0] tmp_16_reg_4983;
wire   [1:0] tmp_17_fu_1528_p4;
reg   [1:0] tmp_17_reg_4991;
wire   [1:0] tmp_18_fu_1538_p4;
reg   [1:0] tmp_18_reg_4999;
wire   [1:0] trunc_ln1348_fu_1548_p1;
reg   [1:0] trunc_ln1348_reg_5007;
wire   [1:0] tmp_20_fu_1632_p4;
reg   [1:0] tmp_20_reg_5016;
wire   [1:0] tmp_21_fu_1642_p4;
reg   [1:0] tmp_21_reg_5022;
wire   [1:0] tmp_22_fu_1652_p4;
reg   [1:0] tmp_22_reg_5028;
wire   [1:0] tmp_23_fu_1662_p4;
reg   [1:0] tmp_23_reg_5035;
wire   [1:0] tmp_24_fu_1672_p4;
reg   [1:0] tmp_24_reg_5042;
wire   [1:0] tmp_25_fu_1682_p4;
reg   [1:0] tmp_25_reg_5049;
wire   [1:0] tmp_26_fu_1692_p4;
reg   [1:0] tmp_26_reg_5056;
wire   [1:0] tmp_27_fu_1702_p4;
reg   [1:0] tmp_27_reg_5064;
wire   [1:0] tmp_28_fu_1712_p4;
reg   [1:0] tmp_28_reg_5072;
wire   [1:0] tmp_29_fu_1722_p4;
reg   [1:0] tmp_29_reg_5080;
wire   [1:0] tmp_30_fu_1732_p4;
reg   [1:0] tmp_30_reg_5088;
wire   [1:0] tmp_31_fu_1742_p4;
reg   [1:0] tmp_31_reg_5096;
wire   [1:0] tmp_32_fu_1752_p4;
reg   [1:0] tmp_32_reg_5104;
wire   [1:0] tmp_33_fu_1762_p4;
reg   [1:0] tmp_33_reg_5112;
wire   [1:0] tmp_34_fu_1772_p4;
reg   [1:0] tmp_34_reg_5120;
reg   [58:0] trunc_ln69_8_reg_5129;
wire   [1:0] tmp_53_fu_1985_p4;
reg   [1:0] tmp_53_reg_5134;
wire   [1:0] tmp_54_fu_1995_p4;
reg   [1:0] tmp_54_reg_5140;
wire   [1:0] tmp_55_fu_2005_p4;
reg   [1:0] tmp_55_reg_5146;
wire   [1:0] tmp_56_fu_2015_p4;
reg   [1:0] tmp_56_reg_5153;
wire   [1:0] tmp_57_fu_2025_p4;
reg   [1:0] tmp_57_reg_5160;
wire   [1:0] tmp_58_fu_2035_p4;
reg   [1:0] tmp_58_reg_5167;
wire   [1:0] tmp_59_fu_2045_p4;
reg   [1:0] tmp_59_reg_5174;
wire   [1:0] tmp_60_fu_2055_p4;
reg   [1:0] tmp_60_reg_5182;
wire   [1:0] tmp_61_fu_2065_p4;
reg   [1:0] tmp_61_reg_5190;
wire   [1:0] tmp_62_fu_2075_p4;
reg   [1:0] tmp_62_reg_5198;
wire   [1:0] tmp_63_fu_2085_p4;
reg   [1:0] tmp_63_reg_5206;
wire   [1:0] tmp_64_fu_2095_p4;
reg   [1:0] tmp_64_reg_5214;
wire   [1:0] tmp_65_fu_2105_p4;
reg   [1:0] tmp_65_reg_5222;
wire   [1:0] tmp_66_fu_2115_p4;
reg   [1:0] tmp_66_reg_5230;
wire   [1:0] trunc_ln1348_1_fu_2125_p1;
reg   [1:0] trunc_ln1348_1_reg_5238;
wire   [1:0] tmp_68_fu_2209_p4;
reg   [1:0] tmp_68_reg_5247;
wire   [1:0] tmp_69_fu_2219_p4;
reg   [1:0] tmp_69_reg_5253;
wire   [1:0] tmp_70_fu_2229_p4;
reg   [1:0] tmp_70_reg_5259;
wire   [1:0] tmp_71_fu_2239_p4;
reg   [1:0] tmp_71_reg_5266;
wire   [1:0] tmp_72_fu_2249_p4;
reg   [1:0] tmp_72_reg_5273;
wire   [1:0] tmp_73_fu_2259_p4;
reg   [1:0] tmp_73_reg_5280;
wire   [1:0] tmp_74_fu_2269_p4;
reg   [1:0] tmp_74_reg_5287;
wire   [1:0] tmp_75_fu_2279_p4;
reg   [1:0] tmp_75_reg_5295;
wire   [1:0] tmp_76_fu_2289_p4;
reg   [1:0] tmp_76_reg_5303;
wire   [1:0] tmp_77_fu_2299_p4;
reg   [1:0] tmp_77_reg_5311;
wire   [1:0] tmp_78_fu_2309_p4;
reg   [1:0] tmp_78_reg_5319;
wire   [1:0] tmp_79_fu_2319_p4;
reg   [1:0] tmp_79_reg_5327;
wire   [1:0] tmp_80_fu_2329_p4;
reg   [1:0] tmp_80_reg_5335;
wire   [1:0] tmp_81_fu_2339_p4;
reg   [1:0] tmp_81_reg_5343;
wire   [1:0] tmp_82_fu_2349_p4;
reg   [1:0] tmp_82_reg_5351;
reg   [58:0] trunc_ln69_3_reg_5360;
wire   [3:0] tmp_43_fu_2986_p4;
reg   [3:0] tmp_43_reg_5365;
wire   [3:0] tmp_44_fu_2996_p4;
reg   [3:0] tmp_44_reg_5370;
wire   [3:0] tmp_45_fu_3006_p4;
reg   [3:0] tmp_45_reg_5375;
wire   [3:0] tmp_46_fu_3016_p4;
reg   [3:0] tmp_46_reg_5380;
wire   [3:0] tmp_47_fu_3026_p4;
reg   [3:0] tmp_47_reg_5385;
wire   [3:0] add_ln691_fu_3076_p2;
reg   [3:0] add_ln691_reg_5391;
reg   [3:0] tmp_48_reg_5396;
reg   [3:0] tmp_49_reg_5401;
reg   [3:0] tmp_50_reg_5406;
reg   [3:0] tmp_51_reg_5411;
wire   [3:0] trunc_ln691_fu_3122_p1;
reg   [3:0] trunc_ln691_reg_5416;
reg   [38:0] trunc_ln691_6_reg_5421;
reg   [6:0] trunc_ln691_1_reg_5426;
wire   [3:0] tmp_91_fu_3693_p4;
reg   [3:0] tmp_91_reg_5431;
wire   [3:0] tmp_92_fu_3703_p4;
reg   [3:0] tmp_92_reg_5436;
wire   [3:0] tmp_93_fu_3713_p4;
reg   [3:0] tmp_93_reg_5441;
wire   [3:0] tmp_94_fu_3723_p4;
reg   [3:0] tmp_94_reg_5446;
wire   [3:0] tmp_95_fu_3733_p4;
reg   [3:0] tmp_95_reg_5451;
wire   [3:0] add_ln691_534_fu_3783_p2;
reg   [3:0] add_ln691_534_reg_5457;
reg   [3:0] tmp_96_reg_5462;
reg   [3:0] tmp_97_reg_5467;
reg   [3:0] tmp_98_reg_5472;
reg   [3:0] tmp_99_reg_5477;
wire   [3:0] trunc_ln691_10_fu_3829_p1;
reg   [3:0] trunc_ln691_10_reg_5482;
reg   [38:0] trunc_ln691_9_reg_5487;
reg   [6:0] trunc_ln691_3_reg_5492;
wire   [6:0] add_ln1497_1_fu_3939_p2;
reg   [6:0] add_ln1497_1_reg_5497;
wire   [6:0] add_ln1497_3_fu_4025_p2;
reg   [6:0] add_ln1497_3_reg_5502;
wire   [15:0] add_ln691_538_fu_4083_p2;
reg    ap_enable_reg_pp0_iter5;
wire    ap_CS_fsm_state10;
wire   [1:0] kh_off_fu_4104_p1;
reg   [1:0] kh_off_reg_5517;
wire   [0:0] kh_off_1_fu_4108_p1;
reg   [0:0] kh_off_1_reg_5524;
wire   [0:0] icmp_ln870_3_fu_4127_p2;
reg   [0:0] icmp_ln870_3_reg_5535;
wire   [0:0] p_Repl2_s_fu_4226_p2;
reg   [0:0] p_Repl2_s_reg_5540;
wire    ap_CS_fsm_state11;
wire   [15:0] select_ln870_fu_4279_p3;
reg   [15:0] select_ln870_reg_5555;
wire    ap_CS_fsm_state13;
wire   [15:0] best_out_V_3_fu_4369_p3;
reg   [15:0] best_out_V_3_reg_5565;
wire    ap_CS_fsm_state14;
wire   [7:0] prediction_V_2_fu_4383_p3;
reg   [7:0] prediction_V_2_reg_5570;
wire   [63:0] o_word_V_3_fu_4397_p3;
reg   [63:0] o_word_V_3_reg_5575;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state4;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg   [15:0] o_V_1_reg_469;
wire    ap_CS_fsm_state15;
reg   [7:0] prediction_V_3_reg_481;
reg   [15:0] best_out_V_reg_493;
reg   [18:0] phi_mul_reg_505;
wire   [63:0] zext_ln534_fu_612_p1;
wire   [63:0] conv_i630_fu_739_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] conv_i615_fu_747_p1;
wire   [63:0] zext_ln534_10_fu_4099_p1;
wire   [63:0] zext_ln534_11_fu_4122_p1;
wire   [0:0] icmp_ln870_fu_628_p2;
wire   [63:0] p_Result_3_fu_633_p3;
wire   [16:0] zext_ln215_fu_588_p1;
wire   [6:0] trunc_ln878_fu_584_p1;
wire   [16:0] ret_fu_592_p2;
wire   [9:0] lshr_ln_fu_602_p4;
wire   [6:0] add_ln1346_1_fu_597_p2;
wire   [5:0] trunc_ln1346_2_fu_647_p1;
wire   [0:0] and_ln608_fu_656_p2;
wire   [0:0] xor_ln608_fu_668_p2;
wire   [0:0] and_ln608_1_fu_673_p2;
wire   [63:0] select_ln608_fu_660_p3;
wire   [0:0] and_ln608_2_fu_686_p2;
wire   [63:0] select_ln608_1_fu_678_p3;
wire   [18:0] zext_ln1346_fu_709_p1;
wire   [18:0] ret_12_fu_713_p2;
wire   [8:0] ret_3_fu_729_p4;
wire   [11:0] ret_s_fu_719_p4;
wire   [63:0] select_ln619_fu_753_p3;
wire   [63:0] select_ln619_1_fu_1022_p3;
wire   [62:0] and_ln_fu_1291_p64;
wire   [63:0] zext_ln692_fu_1389_p1;
wire   [63:0] sub_ln692_fu_1393_p2;
wire   [1:0] tmp_s_fu_1398_p4;
wire   [61:0] and_ln1348_s_fu_1552_p32;
wire   [1:0] tmp_19_fu_1622_p4;
wire   [61:0] and_ln1348_1_fu_1782_p32;
wire   [62:0] zext_ln69_fu_1848_p1;
wire   [62:0] zext_ln1497_fu_1618_p1;
wire   [62:0] add_ln69_fu_1852_p2;
wire   [62:0] and_ln1348_2_fu_1868_p64;
wire   [63:0] zext_ln692_1_fu_1966_p1;
wire   [63:0] sub_ln692_1_fu_1970_p2;
wire   [1:0] tmp_52_fu_1975_p4;
wire   [61:0] and_ln1348_3_fu_2129_p32;
wire   [1:0] tmp_67_fu_2199_p4;
wire   [61:0] and_ln1348_4_fu_2359_p32;
wire   [62:0] zext_ln69_5_fu_2425_p1;
wire   [62:0] zext_ln1497_1_fu_2195_p1;
wire   [62:0] add_ln69_4_fu_2429_p2;
wire   [58:0] and_ln1348_1_cast_fu_2494_p31;
wire   [58:0] and_ln1348_cast_fu_2445_p31;
wire   [59:0] trunc_ln69_7_fu_2592_p31;
wire   [59:0] trunc_ln69_6_fu_2543_p31;
wire   [51:0] trunc_ln1497_3_cast_fu_2690_p27;
wire   [51:0] trunc_ln1497_2_cast_fu_2647_p27;
wire   [58:0] add_ln69_10_fu_2641_p2;
wire   [59:0] zext_ln69_1_fu_2739_p1;
wire   [59:0] add_ln1497_fu_2733_p2;
wire   [35:0] trunc_ln69_cast_fu_2779_p19;
wire   [35:0] trunc_ln69_9_cast_fu_2748_p19;
wire   [51:0] trunc_ln69_10_cast_fu_2816_p4;
wire   [51:0] add_ln69_3_fu_2810_p2;
wire   [35:0] trunc_ln69_11_cast_fu_2848_p4;
wire   [35:0] add_ln69_5_fu_2842_p2;
wire   [51:0] add_ln69_6_fu_2858_p2;
wire   [3:0] tmp_35_fu_2870_p4;
wire   [3:0] tmp_36_fu_2880_p4;
wire   [3:0] tmp_37_fu_2890_p4;
wire   [3:0] tmp_38_fu_2900_p4;
wire   [3:0] tmp_39_fu_2910_p4;
wire   [3:0] tmp_40_fu_2920_p4;
wire   [3:0] trunc_ln1497_fu_2930_p1;
wire   [59:0] add_ln69_2_fu_2826_p2;
wire   [3:0] tmp_41_fu_2966_p4;
wire   [3:0] tmp_42_fu_2976_p4;
wire   [51:0] trunc_ln691_4_fu_3036_p14;
wire   [3:0] zext_ln69_2_fu_2742_p1;
wire   [3:0] trunc_ln69_2_fu_2832_p4;
wire   [3:0] add_ln691_530_fu_3070_p2;
wire   [3:0] zext_ln69_3_fu_2745_p1;
wire   [35:0] add_ln1497_2_fu_2864_p2;
wire   [54:0] zext_ln691_fu_3066_p1;
wire   [54:0] and_ln1_fu_2934_p15;
wire   [54:0] add_ln691_531_fu_3126_p2;
wire   [58:0] and_ln1348_4_cast_fu_3201_p31;
wire   [58:0] and_ln1348_3_cast_fu_3152_p31;
wire   [59:0] trunc_ln69_1_fu_3299_p31;
wire   [59:0] trunc_ln69_s_fu_3250_p31;
wire   [51:0] trunc_ln1497_5_cast_fu_3397_p27;
wire   [51:0] trunc_ln1497_4_cast_fu_3354_p27;
wire   [58:0] add_ln69_11_fu_3348_p2;
wire   [59:0] zext_ln69_6_fu_3446_p1;
wire   [59:0] add_ln1497_7_fu_3440_p2;
wire   [35:0] trunc_ln69_16_cast_fu_3486_p19;
wire   [35:0] trunc_ln69_15_cast_fu_3455_p19;
wire   [51:0] trunc_ln69_17_cast_fu_3523_p4;
wire   [51:0] add_ln69_7_fu_3517_p2;
wire   [35:0] trunc_ln69_18_cast_fu_3555_p4;
wire   [35:0] add_ln69_8_fu_3549_p2;
wire   [51:0] add_ln69_9_fu_3565_p2;
wire   [3:0] tmp_83_fu_3577_p4;
wire   [3:0] tmp_84_fu_3587_p4;
wire   [3:0] tmp_85_fu_3597_p4;
wire   [3:0] tmp_86_fu_3607_p4;
wire   [3:0] tmp_87_fu_3617_p4;
wire   [3:0] tmp_88_fu_3627_p4;
wire   [3:0] trunc_ln1497_2_fu_3637_p1;
wire   [59:0] add_ln69_1_fu_3533_p2;
wire   [3:0] tmp_89_fu_3673_p4;
wire   [3:0] tmp_90_fu_3683_p4;
wire   [51:0] trunc_ln691_7_fu_3743_p14;
wire   [3:0] zext_ln69_7_fu_3449_p1;
wire   [3:0] trunc_ln69_5_fu_3539_p4;
wire   [3:0] add_ln691_533_fu_3777_p2;
wire   [3:0] zext_ln69_8_fu_3452_p1;
wire   [35:0] add_ln1497_8_fu_3571_p2;
wire   [54:0] zext_ln691_2_fu_3773_p1;
wire   [54:0] and_ln1497_2_fu_3641_p15;
wire   [54:0] add_ln691_535_fu_3833_p2;
wire   [38:0] trunc_ln691_5_fu_3878_p11;
wire   [38:0] and_ln2_fu_3859_p11;
wire   [38:0] add_ln1497_4_fu_3897_p2;
wire   [38:0] add_ln691_532_fu_3913_p2;
wire   [6:0] trunc_ln_fu_3906_p3;
wire   [6:0] zext_ln691_1_fu_3903_p1;
wire   [6:0] trunc_ln4_fu_3918_p4;
wire   [6:0] add_ln1497_6_fu_3934_p2;
wire   [6:0] add_ln1497_5_fu_3928_p2;
wire   [38:0] trunc_ln691_8_fu_3964_p11;
wire   [38:0] and_ln691_1_fu_3945_p11;
wire   [38:0] add_ln1497_9_fu_3983_p2;
wire   [38:0] add_ln691_536_fu_3999_p2;
wire   [6:0] trunc_ln691_2_fu_3992_p3;
wire   [6:0] zext_ln691_3_fu_3989_p1;
wire   [6:0] trunc_ln1497_1_fu_4004_p4;
wire   [6:0] add_ln1497_11_fu_4020_p2;
wire   [6:0] add_ln1497_10_fu_4014_p2;
wire   [7:0] shl_ln_fu_4031_p3;
wire   [8:0] zext_ln69_4_fu_4038_p1;
wire   [8:0] sub_ln69_fu_4042_p2;
wire   [7:0] shl_ln1497_1_fu_4052_p3;
wire   [8:0] zext_ln69_9_fu_4059_p1;
wire   [8:0] sub_ln69_1_fu_4063_p2;
wire  signed [9:0] sext_ln691_fu_4069_p1;
wire  signed [9:0] sext_ln619_fu_4048_p1;
wire   [9:0] add_ln691_537_fu_4073_p2;
wire  signed [15:0] sext_ln691_447_fu_4079_p1;
wire   [5:0] ret_4_fu_4089_p4;
wire   [5:0] ret_5_fu_4112_p4;
wire   [0:0] icmp_ln648_2_fu_4191_p2;
wire   [15:0] tmp_920_fu_4157_p4;
wire   [15:0] tmp_919_fu_4147_p4;
wire   [0:0] icmp_ln648_1_fu_4186_p2;
wire   [0:0] icmp_ln648_fu_4181_p2;
wire   [15:0] tmp_918_fu_4143_p1;
wire   [15:0] tmp_917_fu_4133_p4;
wire   [0:0] or_ln648_fu_4204_p2;
wire   [15:0] select_ln648_fu_4196_p3;
wire   [15:0] select_ln648_1_fu_4210_p3;
wire   [15:0] nc_V_8_fu_4218_p3;
wire   [15:0] p_Result_1_fu_4171_p4;
wire   [15:0] p_Result_s_fu_4167_p1;
wire   [9:0] trunc_ln728_fu_4239_p1;
wire  signed [19:0] r_V_fu_4243_p3;
wire  signed [15:0] ki_V_2_fu_4232_p3;
wire   [15:0] tmp_103_fu_4259_p4;
wire   [15:0] tmp_104_fu_4269_p4;
wire  signed [27:0] rhs_4_fu_4286_p3;
wire   [31:0] zext_ln545_fu_4297_p1;
wire   [31:0] zext_ln844_fu_4300_p1;
wire  signed [33:0] grp_fu_4404_p3;
wire   [19:0] out_V_fu_4312_p4;
wire  signed [21:0] sext_ln727_2_fu_4321_p1;
wire   [21:0] shl_ln5_fu_4325_p3;
wire   [13:0] best_out_V_1_fu_4339_p4;
wire  signed [15:0] sext_ln708_fu_4348_p1;
wire   [0:0] icmp_ln1494_fu_4333_p2;
wire   [0:0] or_ln1494_fu_4359_p2;
wire   [0:0] or_ln1494_1_fu_4364_p2;
wire   [15:0] best_out_V_2_fu_4352_p3;
wire   [7:0] prediction_V_1_fu_4377_p3;
reg   [63:0] p_Result_2_fu_4303_p4;
wire   [63:0] o_word_V_2_fu_4391_p3;
reg   [9:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
end

top_mac_muladd_20s_16s_28s_34_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 34 ))
mac_muladd_20s_16s_28s_34_4_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(r_V_fu_4243_p3),
    .din1(ki_V_2_fu_4232_p3),
    .din2(rhs_4_fu_4286_p3),
    .ce(1'b1),
    .dout(grp_fu_4404_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state4) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state4)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state4);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        best_out_V_reg_493 <= 16'd49152;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        best_out_V_reg_493 <= best_out_V_3_reg_5565;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln878_fu_698_p2 == 1'd1))) begin
        i_V_8_reg_517 <= i_V_fu_703_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        i_V_8_reg_517 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        o_V_1_reg_469 <= 16'd0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        o_V_1_reg_469 <= o_V_reg_4474;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        phi_mul_reg_505 <= 19'd0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        phi_mul_reg_505 <= add_ln605_reg_4479;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        prediction_V_3_reg_481 <= 8'd255;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        prediction_V_3_reg_481 <= prediction_V_2_reg_5570;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln878_reg_4534_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sum_V_reg_528 <= add_ln691_538_fu_4083_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        sum_V_reg_528 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln878_reg_4534_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln1497_1_reg_5497 <= add_ln1497_1_fu_3939_p2;
        add_ln1497_3_reg_5502 <= add_ln1497_3_fu_4025_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln605_reg_4479 <= add_ln605_fu_574_p2;
        o_V_reg_4474 <= o_V_fu_568_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln878_reg_4534_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln691_534_reg_5457 <= add_ln691_534_fu_3783_p2;
        add_ln691_reg_5391 <= add_ln691_fu_3076_p2;
        tmp_43_reg_5365 <= {{add_ln69_2_fu_2826_p2[43:40]}};
        tmp_44_reg_5370 <= {{add_ln69_2_fu_2826_p2[35:32]}};
        tmp_45_reg_5375 <= {{add_ln69_2_fu_2826_p2[27:24]}};
        tmp_46_reg_5380 <= {{add_ln69_2_fu_2826_p2[19:16]}};
        tmp_47_reg_5385 <= {{add_ln69_2_fu_2826_p2[11:8]}};
        tmp_48_reg_5396 <= {{add_ln1497_2_fu_2864_p2[35:32]}};
        tmp_49_reg_5401 <= {{add_ln1497_2_fu_2864_p2[27:24]}};
        tmp_50_reg_5406 <= {{add_ln1497_2_fu_2864_p2[19:16]}};
        tmp_51_reg_5411 <= {{add_ln1497_2_fu_2864_p2[11:8]}};
        tmp_91_reg_5431 <= {{add_ln69_1_fu_3533_p2[43:40]}};
        tmp_92_reg_5436 <= {{add_ln69_1_fu_3533_p2[35:32]}};
        tmp_93_reg_5441 <= {{add_ln69_1_fu_3533_p2[27:24]}};
        tmp_94_reg_5446 <= {{add_ln69_1_fu_3533_p2[19:16]}};
        tmp_95_reg_5451 <= {{add_ln69_1_fu_3533_p2[11:8]}};
        tmp_96_reg_5462 <= {{add_ln1497_8_fu_3571_p2[35:32]}};
        tmp_97_reg_5467 <= {{add_ln1497_8_fu_3571_p2[27:24]}};
        tmp_98_reg_5472 <= {{add_ln1497_8_fu_3571_p2[19:16]}};
        tmp_99_reg_5477 <= {{add_ln1497_8_fu_3571_p2[11:8]}};
        trunc_ln691_10_reg_5482 <= trunc_ln691_10_fu_3829_p1;
        trunc_ln691_1_reg_5426 <= {{add_ln691_531_fu_3126_p2[22:16]}};
        trunc_ln691_3_reg_5492 <= {{add_ln691_535_fu_3833_p2[22:16]}};
        trunc_ln691_6_reg_5421 <= {{add_ln691_531_fu_3126_p2[54:16]}};
        trunc_ln691_9_reg_5487 <= {{add_ln691_535_fu_3833_p2[54:16]}};
        trunc_ln691_reg_5416 <= trunc_ln691_fu_3122_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        best_out_V_3_reg_5565 <= best_out_V_3_fu_4369_p3;
        o_word_V_3_reg_5575 <= o_word_V_3_fu_4397_p3;
        prediction_V_2_reg_5570 <= prediction_V_2_fu_4383_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        cmp_i_i426_reg_4451 <= cmp_i_i426_fu_548_p2;
        lhs_reg_4441[15 : 0] <= lhs_fu_540_p1[15 : 0];
        trunc_ln1346_1_reg_4464 <= trunc_ln1346_1_fu_558_p1;
        trunc_ln1346_reg_4459 <= trunc_ln1346_fu_554_p1;
        xor_ln689_reg_4469 <= xor_ln689_fu_562_p2;
        zext_ln613_reg_4446[15 : 0] <= zext_ln613_fu_544_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln605_fu_579_p2 == 1'd0))) begin
        dmem_V_0_0_addr_reg_4494 <= zext_ln534_fu_612_p1;
        dmem_V_0_1_addr_reg_4499 <= zext_ln534_fu_612_p1;
        dmem_V_1_0_addr_reg_4504 <= zext_ln534_fu_612_p1;
        dmem_V_1_1_addr_reg_4509 <= zext_ln534_fu_612_p1;
        tmp_reg_4487 <= add_ln1346_1_fu_597_p2[32'd6];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        icmp_ln870_3_reg_5535 <= icmp_ln870_3_fu_4127_p2;
        kh_off_1_reg_5524 <= kh_off_1_fu_4108_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln878_reg_4534 <= icmp_ln878_fu_698_p2;
        icmp_ln878_reg_4534_pp0_iter1_reg <= icmp_ln878_reg_4534;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln878_reg_4534_pp0_iter2_reg <= icmp_ln878_reg_4534_pp0_iter1_reg;
        icmp_ln878_reg_4534_pp0_iter3_reg <= icmp_ln878_reg_4534_pp0_iter2_reg;
        icmp_ln878_reg_4534_pp0_iter4_reg <= icmp_ln878_reg_4534_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (cmp_i_i426_reg_4451 == 1'd1))) begin
        kh_off_reg_5517 <= kh_off_fu_4104_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (cmp_i_i426_reg_4451 == 1'd1))) begin
        o_offset_reg_4522 <= o_offset_fu_651_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        o_word_V_4_reg_4527 <= o_word_V_4_fu_690_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (cmp_i_i426_reg_4451 == 1'd1))) begin
        p_Repl2_s_reg_5540 <= p_Repl2_s_fu_4226_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (cmp_i_i426_reg_4451 == 1'd0))) begin
        prediction_V_reg_4517 <= prediction_V_fu_643_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        select_ln870_reg_5555 <= select_ln870_fu_4279_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln878_reg_4534_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_10_reg_4936 <= {{sub_ln692_fu_1393_p2[37:36]}};
        tmp_11_reg_4943 <= {{sub_ln692_fu_1393_p2[33:32]}};
        tmp_12_reg_4951 <= {{sub_ln692_fu_1393_p2[29:28]}};
        tmp_13_reg_4959 <= {{sub_ln692_fu_1393_p2[25:24]}};
        tmp_14_reg_4967 <= {{sub_ln692_fu_1393_p2[21:20]}};
        tmp_15_reg_4975 <= {{sub_ln692_fu_1393_p2[17:16]}};
        tmp_16_reg_4983 <= {{sub_ln692_fu_1393_p2[13:12]}};
        tmp_17_reg_4991 <= {{sub_ln692_fu_1393_p2[9:8]}};
        tmp_18_reg_4999 <= {{sub_ln692_fu_1393_p2[5:4]}};
        tmp_20_reg_5016 <= {{sub_ln692_fu_1393_p2[59:58]}};
        tmp_21_reg_5022 <= {{sub_ln692_fu_1393_p2[55:54]}};
        tmp_22_reg_5028 <= {{sub_ln692_fu_1393_p2[51:50]}};
        tmp_23_reg_5035 <= {{sub_ln692_fu_1393_p2[47:46]}};
        tmp_24_reg_5042 <= {{sub_ln692_fu_1393_p2[43:42]}};
        tmp_25_reg_5049 <= {{sub_ln692_fu_1393_p2[39:38]}};
        tmp_26_reg_5056 <= {{sub_ln692_fu_1393_p2[35:34]}};
        tmp_27_reg_5064 <= {{sub_ln692_fu_1393_p2[31:30]}};
        tmp_28_reg_5072 <= {{sub_ln692_fu_1393_p2[27:26]}};
        tmp_29_reg_5080 <= {{sub_ln692_fu_1393_p2[23:22]}};
        tmp_30_reg_5088 <= {{sub_ln692_fu_1393_p2[19:18]}};
        tmp_31_reg_5096 <= {{sub_ln692_fu_1393_p2[15:14]}};
        tmp_32_reg_5104 <= {{sub_ln692_fu_1393_p2[11:10]}};
        tmp_33_reg_5112 <= {{sub_ln692_fu_1393_p2[7:6]}};
        tmp_34_reg_5120 <= {{sub_ln692_fu_1393_p2[3:2]}};
        tmp_53_reg_5134 <= {{sub_ln692_1_fu_1970_p2[57:56]}};
        tmp_54_reg_5140 <= {{sub_ln692_1_fu_1970_p2[53:52]}};
        tmp_55_reg_5146 <= {{sub_ln692_1_fu_1970_p2[49:48]}};
        tmp_56_reg_5153 <= {{sub_ln692_1_fu_1970_p2[45:44]}};
        tmp_57_reg_5160 <= {{sub_ln692_1_fu_1970_p2[41:40]}};
        tmp_58_reg_5167 <= {{sub_ln692_1_fu_1970_p2[37:36]}};
        tmp_59_reg_5174 <= {{sub_ln692_1_fu_1970_p2[33:32]}};
        tmp_5_reg_4903 <= {{sub_ln692_fu_1393_p2[57:56]}};
        tmp_60_reg_5182 <= {{sub_ln692_1_fu_1970_p2[29:28]}};
        tmp_61_reg_5190 <= {{sub_ln692_1_fu_1970_p2[25:24]}};
        tmp_62_reg_5198 <= {{sub_ln692_1_fu_1970_p2[21:20]}};
        tmp_63_reg_5206 <= {{sub_ln692_1_fu_1970_p2[17:16]}};
        tmp_64_reg_5214 <= {{sub_ln692_1_fu_1970_p2[13:12]}};
        tmp_65_reg_5222 <= {{sub_ln692_1_fu_1970_p2[9:8]}};
        tmp_66_reg_5230 <= {{sub_ln692_1_fu_1970_p2[5:4]}};
        tmp_68_reg_5247 <= {{sub_ln692_1_fu_1970_p2[59:58]}};
        tmp_69_reg_5253 <= {{sub_ln692_1_fu_1970_p2[55:54]}};
        tmp_6_reg_4909 <= {{sub_ln692_fu_1393_p2[53:52]}};
        tmp_70_reg_5259 <= {{sub_ln692_1_fu_1970_p2[51:50]}};
        tmp_71_reg_5266 <= {{sub_ln692_1_fu_1970_p2[47:46]}};
        tmp_72_reg_5273 <= {{sub_ln692_1_fu_1970_p2[43:42]}};
        tmp_73_reg_5280 <= {{sub_ln692_1_fu_1970_p2[39:38]}};
        tmp_74_reg_5287 <= {{sub_ln692_1_fu_1970_p2[35:34]}};
        tmp_75_reg_5295 <= {{sub_ln692_1_fu_1970_p2[31:30]}};
        tmp_76_reg_5303 <= {{sub_ln692_1_fu_1970_p2[27:26]}};
        tmp_77_reg_5311 <= {{sub_ln692_1_fu_1970_p2[23:22]}};
        tmp_78_reg_5319 <= {{sub_ln692_1_fu_1970_p2[19:18]}};
        tmp_79_reg_5327 <= {{sub_ln692_1_fu_1970_p2[15:14]}};
        tmp_7_reg_4915 <= {{sub_ln692_fu_1393_p2[49:48]}};
        tmp_80_reg_5335 <= {{sub_ln692_1_fu_1970_p2[11:10]}};
        tmp_81_reg_5343 <= {{sub_ln692_1_fu_1970_p2[7:6]}};
        tmp_82_reg_5351 <= {{sub_ln692_1_fu_1970_p2[3:2]}};
        tmp_8_reg_4922 <= {{sub_ln692_fu_1393_p2[45:44]}};
        tmp_9_reg_4929 <= {{sub_ln692_fu_1393_p2[41:40]}};
        trunc_ln1348_1_reg_5238 <= trunc_ln1348_1_fu_2125_p1;
        trunc_ln1348_reg_5007 <= trunc_ln1348_fu_1548_p1;
        trunc_ln69_3_reg_5360 <= {{add_ln69_4_fu_2429_p2[62:4]}};
        trunc_ln69_8_reg_5129 <= {{add_ln69_fu_1852_p2[62:4]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln878_reg_4534 == 1'd1))) begin
        tmp_851_reg_4578 <= xor_ln1350_fu_760_p2[32'd63];
        tmp_852_reg_4583 <= xor_ln1350_fu_760_p2[32'd61];
        tmp_853_reg_4588 <= xor_ln1350_fu_760_p2[32'd59];
        tmp_854_reg_4593 <= xor_ln1350_fu_760_p2[32'd57];
        tmp_855_reg_4598 <= xor_ln1350_fu_760_p2[32'd55];
        tmp_856_reg_4603 <= xor_ln1350_fu_760_p2[32'd53];
        tmp_857_reg_4608 <= xor_ln1350_fu_760_p2[32'd51];
        tmp_858_reg_4613 <= xor_ln1350_fu_760_p2[32'd49];
        tmp_859_reg_4618 <= xor_ln1350_fu_760_p2[32'd47];
        tmp_860_reg_4623 <= xor_ln1350_fu_760_p2[32'd45];
        tmp_861_reg_4628 <= xor_ln1350_fu_760_p2[32'd43];
        tmp_862_reg_4633 <= xor_ln1350_fu_760_p2[32'd41];
        tmp_863_reg_4638 <= xor_ln1350_fu_760_p2[32'd39];
        tmp_864_reg_4643 <= xor_ln1350_fu_760_p2[32'd37];
        tmp_865_reg_4648 <= xor_ln1350_fu_760_p2[32'd35];
        tmp_866_reg_4653 <= xor_ln1350_fu_760_p2[32'd33];
        tmp_867_reg_4658 <= xor_ln1350_fu_760_p2[32'd31];
        tmp_868_reg_4663 <= xor_ln1350_fu_760_p2[32'd29];
        tmp_869_reg_4668 <= xor_ln1350_fu_760_p2[32'd27];
        tmp_870_reg_4673 <= xor_ln1350_fu_760_p2[32'd25];
        tmp_871_reg_4678 <= xor_ln1350_fu_760_p2[32'd23];
        tmp_872_reg_4683 <= xor_ln1350_fu_760_p2[32'd21];
        tmp_873_reg_4688 <= xor_ln1350_fu_760_p2[32'd19];
        tmp_874_reg_4693 <= xor_ln1350_fu_760_p2[32'd17];
        tmp_875_reg_4698 <= xor_ln1350_fu_760_p2[32'd15];
        tmp_876_reg_4703 <= xor_ln1350_fu_760_p2[32'd13];
        tmp_877_reg_4708 <= xor_ln1350_fu_760_p2[32'd11];
        tmp_878_reg_4713 <= xor_ln1350_fu_760_p2[32'd9];
        tmp_879_reg_4718 <= xor_ln1350_fu_760_p2[32'd7];
        tmp_880_reg_4723 <= xor_ln1350_fu_760_p2[32'd5];
        tmp_881_reg_4728 <= xor_ln1350_fu_760_p2[32'd3];
        tmp_882_reg_4733 <= xor_ln1350_fu_760_p2[32'd1];
        tmp_883_reg_4743 <= xor_ln1350_1_fu_1029_p2[32'd63];
        tmp_884_reg_4748 <= xor_ln1350_1_fu_1029_p2[32'd61];
        tmp_885_reg_4753 <= xor_ln1350_1_fu_1029_p2[32'd59];
        tmp_886_reg_4758 <= xor_ln1350_1_fu_1029_p2[32'd57];
        tmp_887_reg_4763 <= xor_ln1350_1_fu_1029_p2[32'd55];
        tmp_888_reg_4768 <= xor_ln1350_1_fu_1029_p2[32'd53];
        tmp_889_reg_4773 <= xor_ln1350_1_fu_1029_p2[32'd51];
        tmp_890_reg_4778 <= xor_ln1350_1_fu_1029_p2[32'd49];
        tmp_891_reg_4783 <= xor_ln1350_1_fu_1029_p2[32'd47];
        tmp_892_reg_4788 <= xor_ln1350_1_fu_1029_p2[32'd45];
        tmp_893_reg_4793 <= xor_ln1350_1_fu_1029_p2[32'd43];
        tmp_894_reg_4798 <= xor_ln1350_1_fu_1029_p2[32'd41];
        tmp_895_reg_4803 <= xor_ln1350_1_fu_1029_p2[32'd39];
        tmp_896_reg_4808 <= xor_ln1350_1_fu_1029_p2[32'd37];
        tmp_897_reg_4813 <= xor_ln1350_1_fu_1029_p2[32'd35];
        tmp_898_reg_4818 <= xor_ln1350_1_fu_1029_p2[32'd33];
        tmp_899_reg_4823 <= xor_ln1350_1_fu_1029_p2[32'd31];
        tmp_900_reg_4828 <= xor_ln1350_1_fu_1029_p2[32'd29];
        tmp_901_reg_4833 <= xor_ln1350_1_fu_1029_p2[32'd27];
        tmp_902_reg_4838 <= xor_ln1350_1_fu_1029_p2[32'd25];
        tmp_903_reg_4843 <= xor_ln1350_1_fu_1029_p2[32'd23];
        tmp_904_reg_4848 <= xor_ln1350_1_fu_1029_p2[32'd21];
        tmp_905_reg_4853 <= xor_ln1350_1_fu_1029_p2[32'd19];
        tmp_906_reg_4858 <= xor_ln1350_1_fu_1029_p2[32'd17];
        tmp_907_reg_4863 <= xor_ln1350_1_fu_1029_p2[32'd15];
        tmp_908_reg_4868 <= xor_ln1350_1_fu_1029_p2[32'd13];
        tmp_909_reg_4873 <= xor_ln1350_1_fu_1029_p2[32'd11];
        tmp_910_reg_4878 <= xor_ln1350_1_fu_1029_p2[32'd9];
        tmp_911_reg_4883 <= xor_ln1350_1_fu_1029_p2[32'd7];
        tmp_912_reg_4888 <= xor_ln1350_1_fu_1029_p2[32'd5];
        tmp_913_reg_4893 <= xor_ln1350_1_fu_1029_p2[32'd3];
        tmp_914_reg_4898 <= xor_ln1350_1_fu_1029_p2[32'd1];
        xor_ln1350_1_reg_4738 <= xor_ln1350_1_fu_1029_p2;
        xor_ln1350_reg_4573 <= xor_ln1350_fu_760_p2;
    end
end

always @ (*) begin
    if ((icmp_ln878_fu_698_p2 == 1'd0)) begin
        ap_condition_pp0_exit_iter0_state4 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state4 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln605_fu_579_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln605_fu_579_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        dmem_V_0_0_address0 = dmem_V_0_0_addr_reg_4494;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        dmem_V_0_0_address0 = conv_i630_fu_739_p1;
    end else if (((d_o_idx_read_read_fu_314_p2 == 1'd0) & (icmp_ln870_fu_628_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln605_fu_579_p2 == 1'd1))) begin
        dmem_V_0_0_address0 = 10'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln605_fu_579_p2 == 1'd0))) begin
        dmem_V_0_0_address0 = zext_ln534_fu_612_p1;
    end else begin
        dmem_V_0_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | ((d_o_idx_read_read_fu_314_p2 == 1'd0) & (icmp_ln870_fu_628_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln605_fu_579_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln605_fu_579_p2 == 1'd0)))) begin
        dmem_V_0_0_ce0 = 1'b1;
    end else begin
        dmem_V_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        dmem_V_0_0_d0 = o_word_V_3_reg_5575;
    end else if (((d_o_idx_read_read_fu_314_p2 == 1'd0) & (icmp_ln870_fu_628_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln605_fu_579_p2 == 1'd1))) begin
        dmem_V_0_0_d0 = p_Result_3_fu_633_p3;
    end else begin
        dmem_V_0_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((d_o_idx_read_read_fu_314_p2 == 1'd0) & (icmp_ln870_fu_628_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln605_fu_579_p2 == 1'd1)) | ((d_o_idx_read_read_fu_314_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state15) & (tmp_reg_4487 == 1'd0)))) begin
        dmem_V_0_0_we0 = 1'b1;
    end else begin
        dmem_V_0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        dmem_V_0_1_address0 = dmem_V_0_1_addr_reg_4499;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        dmem_V_0_1_address0 = conv_i630_fu_739_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dmem_V_0_1_address0 = zext_ln534_fu_612_p1;
    end else begin
        dmem_V_0_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        dmem_V_0_1_ce0 = 1'b1;
    end else begin
        dmem_V_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_idx_read_read_fu_314_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state15) & (tmp_reg_4487 == 1'd1))) begin
        dmem_V_0_1_we0 = 1'b1;
    end else begin
        dmem_V_0_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        dmem_V_1_0_address0 = dmem_V_1_0_addr_reg_4504;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        dmem_V_1_0_address0 = conv_i630_fu_739_p1;
    end else if (((d_o_idx_read_read_fu_314_p2 == 1'd1) & (icmp_ln870_fu_628_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln605_fu_579_p2 == 1'd1))) begin
        dmem_V_1_0_address0 = 10'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln605_fu_579_p2 == 1'd0))) begin
        dmem_V_1_0_address0 = zext_ln534_fu_612_p1;
    end else begin
        dmem_V_1_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | ((d_o_idx_read_read_fu_314_p2 == 1'd1) & (icmp_ln870_fu_628_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln605_fu_579_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln605_fu_579_p2 == 1'd0)))) begin
        dmem_V_1_0_ce0 = 1'b1;
    end else begin
        dmem_V_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        dmem_V_1_0_d0 = o_word_V_3_reg_5575;
    end else if (((d_o_idx_read_read_fu_314_p2 == 1'd1) & (icmp_ln870_fu_628_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln605_fu_579_p2 == 1'd1))) begin
        dmem_V_1_0_d0 = p_Result_3_fu_633_p3;
    end else begin
        dmem_V_1_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((d_o_idx_read_read_fu_314_p2 == 1'd1) & (icmp_ln870_fu_628_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln605_fu_579_p2 == 1'd1)) | ((d_o_idx_read_read_fu_314_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15) & (tmp_reg_4487 == 1'd0)))) begin
        dmem_V_1_0_we0 = 1'b1;
    end else begin
        dmem_V_1_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        dmem_V_1_1_address0 = dmem_V_1_1_addr_reg_4509;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        dmem_V_1_1_address0 = conv_i630_fu_739_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dmem_V_1_1_address0 = zext_ln534_fu_612_p1;
    end else begin
        dmem_V_1_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        dmem_V_1_1_ce0 = 1'b1;
    end else begin
        dmem_V_1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_idx_read_read_fu_314_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15) & (tmp_reg_4487 == 1'd1))) begin
        dmem_V_1_1_we0 = 1'b1;
    end else begin
        dmem_V_1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        kh_mem_V_ce0 = 1'b1;
    end else begin
        kh_mem_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        kh_mem_V_ce1 = 1'b1;
    end else begin
        kh_mem_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        wt_mem_V_0_ce0 = 1'b1;
    end else begin
        wt_mem_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        wt_mem_V_1_ce0 = 1'b1;
    end else begin
        wt_mem_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln605_fu_579_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln878_fu_698_p2 == 1'd0)) & ~((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln878_fu_698_p2 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1346_1_fu_597_p2 = (trunc_ln878_fu_584_p1 + trunc_ln1346_1_reg_4464);

assign add_ln1497_10_fu_4014_p2 = (trunc_ln691_2_fu_3992_p3 + zext_ln691_3_fu_3989_p1);

assign add_ln1497_11_fu_4020_p2 = (trunc_ln691_3_reg_5492 + trunc_ln1497_1_fu_4004_p4);

assign add_ln1497_1_fu_3939_p2 = (add_ln1497_6_fu_3934_p2 + add_ln1497_5_fu_3928_p2);

assign add_ln1497_2_fu_2864_p2 = (trunc_ln69_11_cast_fu_2848_p4 + add_ln69_5_fu_2842_p2);

assign add_ln1497_3_fu_4025_p2 = (add_ln1497_11_fu_4020_p2 + add_ln1497_10_fu_4014_p2);

assign add_ln1497_4_fu_3897_p2 = (trunc_ln691_5_fu_3878_p11 + and_ln2_fu_3859_p11);

assign add_ln1497_5_fu_3928_p2 = (trunc_ln_fu_3906_p3 + zext_ln691_1_fu_3903_p1);

assign add_ln1497_6_fu_3934_p2 = (trunc_ln691_1_reg_5426 + trunc_ln4_fu_3918_p4);

assign add_ln1497_7_fu_3440_p2 = (trunc_ln69_1_fu_3299_p31 + trunc_ln69_s_fu_3250_p31);

assign add_ln1497_8_fu_3571_p2 = (trunc_ln69_18_cast_fu_3555_p4 + add_ln69_8_fu_3549_p2);

assign add_ln1497_9_fu_3983_p2 = (trunc_ln691_8_fu_3964_p11 + and_ln691_1_fu_3945_p11);

assign add_ln1497_fu_2733_p2 = (trunc_ln69_7_fu_2592_p31 + trunc_ln69_6_fu_2543_p31);

assign add_ln605_fu_574_p2 = (phi_mul_reg_505 + zext_ln613_reg_4446);

assign add_ln691_530_fu_3070_p2 = (zext_ln69_2_fu_2742_p1 + trunc_ln69_2_fu_2832_p4);

assign add_ln691_531_fu_3126_p2 = (zext_ln691_fu_3066_p1 + and_ln1_fu_2934_p15);

assign add_ln691_532_fu_3913_p2 = (trunc_ln691_6_reg_5421 + add_ln1497_4_fu_3897_p2);

assign add_ln691_533_fu_3777_p2 = (zext_ln69_7_fu_3449_p1 + trunc_ln69_5_fu_3539_p4);

assign add_ln691_534_fu_3783_p2 = (add_ln691_533_fu_3777_p2 + zext_ln69_8_fu_3452_p1);

assign add_ln691_535_fu_3833_p2 = (zext_ln691_2_fu_3773_p1 + and_ln1497_2_fu_3641_p15);

assign add_ln691_536_fu_3999_p2 = (trunc_ln691_9_reg_5487 + add_ln1497_9_fu_3983_p2);

assign add_ln691_537_fu_4073_p2 = ($signed(sext_ln691_fu_4069_p1) + $signed(sext_ln619_fu_4048_p1));

assign add_ln691_538_fu_4083_p2 = ($signed(sum_V_reg_528) + $signed(sext_ln691_447_fu_4079_p1));

assign add_ln691_fu_3076_p2 = (add_ln691_530_fu_3070_p2 + zext_ln69_3_fu_2745_p1);

assign add_ln69_10_fu_2641_p2 = (and_ln1348_1_cast_fu_2494_p31 + and_ln1348_cast_fu_2445_p31);

assign add_ln69_11_fu_3348_p2 = (and_ln1348_4_cast_fu_3201_p31 + and_ln1348_3_cast_fu_3152_p31);

assign add_ln69_1_fu_3533_p2 = (zext_ln69_6_fu_3446_p1 + add_ln1497_7_fu_3440_p2);

assign add_ln69_2_fu_2826_p2 = (zext_ln69_1_fu_2739_p1 + add_ln1497_fu_2733_p2);

assign add_ln69_3_fu_2810_p2 = (trunc_ln1497_3_cast_fu_2690_p27 + trunc_ln1497_2_cast_fu_2647_p27);

assign add_ln69_4_fu_2429_p2 = (zext_ln69_5_fu_2425_p1 + zext_ln1497_1_fu_2195_p1);

assign add_ln69_5_fu_2842_p2 = (trunc_ln69_cast_fu_2779_p19 + trunc_ln69_9_cast_fu_2748_p19);

assign add_ln69_6_fu_2858_p2 = (trunc_ln69_10_cast_fu_2816_p4 + add_ln69_3_fu_2810_p2);

assign add_ln69_7_fu_3517_p2 = (trunc_ln1497_5_cast_fu_3397_p27 + trunc_ln1497_4_cast_fu_3354_p27);

assign add_ln69_8_fu_3549_p2 = (trunc_ln69_16_cast_fu_3486_p19 + trunc_ln69_15_cast_fu_3455_p19);

assign add_ln69_9_fu_3565_p2 = (trunc_ln69_17_cast_fu_3523_p4 + add_ln69_7_fu_3517_p2);

assign add_ln69_fu_1852_p2 = (zext_ln69_fu_1848_p1 + zext_ln1497_fu_1618_p1);

assign and_ln1348_1_cast_fu_2494_p31 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{1'd0}, {tmp_20_reg_5016}}}, {2'd0}}}, {tmp_21_reg_5022}}}, {2'd0}}}, {tmp_22_reg_5028}}}, {2'd0}}}, {tmp_23_reg_5035}}}, {2'd0}}}, {tmp_24_reg_5042}}}, {2'd0}}}, {tmp_25_reg_5049}}}, {2'd0}}}, {tmp_26_reg_5056}}}, {2'd0}}}, {tmp_27_reg_5064}}}, {2'd0}}}, {tmp_28_reg_5072}}}, {2'd0}}}, {tmp_29_reg_5080}}}, {2'd0}}}, {tmp_30_reg_5088}}}, {2'd0}}}, {tmp_31_reg_5096}}}, {2'd0}}}, {tmp_32_reg_5104}}}, {2'd0}}}, {tmp_33_reg_5112}}}, {2'd0}}}, {tmp_34_reg_5120}};

assign and_ln1348_1_fu_1782_p32 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_19_fu_1622_p4}, {2'd0}}, {tmp_20_fu_1632_p4}}, {2'd0}}, {tmp_21_fu_1642_p4}}, {2'd0}}, {tmp_22_fu_1652_p4}}, {2'd0}}, {tmp_23_fu_1662_p4}}, {2'd0}}, {tmp_24_fu_1672_p4}}, {2'd0}}, {tmp_25_fu_1682_p4}}, {2'd0}}, {tmp_26_fu_1692_p4}}, {2'd0}}, {tmp_27_fu_1702_p4}}, {2'd0}}, {tmp_28_fu_1712_p4}}, {2'd0}}, {tmp_29_fu_1722_p4}}, {2'd0}}, {tmp_30_fu_1732_p4}}, {2'd0}}, {tmp_31_fu_1742_p4}}, {2'd0}}, {tmp_32_fu_1752_p4}}, {2'd0}}, {tmp_33_fu_1762_p4}}, {2'd0}}, {tmp_34_fu_1772_p4}};

assign and_ln1348_2_fu_1868_p64 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_883_reg_4743}, {1'd0}}, {tmp_884_reg_4748}}, {1'd0}}, {tmp_885_reg_4753}}, {1'd0}}, {tmp_886_reg_4758}}, {1'd0}}, {tmp_887_reg_4763}}, {1'd0}}, {tmp_888_reg_4768}}, {1'd0}}, {tmp_889_reg_4773}}, {1'd0}}, {tmp_890_reg_4778}}, {1'd0}}, {tmp_891_reg_4783}}, {1'd0}}, {tmp_892_reg_4788}}, {1'd0}}, {tmp_893_reg_4793}}, {1'd0}}, {tmp_894_reg_4798}}, {1'd0}}, {tmp_895_reg_4803}}, {1'd0}}, {tmp_896_reg_4808}}, {1'd0}}, {tmp_897_reg_4813}}, {1'd0}}, {tmp_898_reg_4818}}, {1'd0}}, {tmp_899_reg_4823}}, {1'd0}}, {tmp_900_reg_4828}}, {1'd0}}, {tmp_901_reg_4833}}, {1'd0}}, {tmp_902_reg_4838}}, {1'd0}}, {tmp_903_reg_4843}}, {1'd0}}, {tmp_904_reg_4848}}, {1'd0}}, {tmp_905_reg_4853}}, {1'd0}}, {tmp_906_reg_4858}}, {1'd0}}, {tmp_907_reg_4863}}, {1'd0}}, {tmp_908_reg_4868}}, {1'd0}}, {tmp_909_reg_4873}}, {1'd0}}, {tmp_910_reg_4878}}, {1'd0}}, {tmp_911_reg_4883}}, {1'd0}}, {tmp_912_reg_4888}}, {1'd0}}, {tmp_913_reg_4893}}, {1'd0}}, {tmp_914_reg_4898}};

assign and_ln1348_3_cast_fu_3152_p31 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{1'd0}, {tmp_53_reg_5134}}}, {2'd0}}}, {tmp_54_reg_5140}}}, {2'd0}}}, {tmp_55_reg_5146}}}, {2'd0}}}, {tmp_56_reg_5153}}}, {2'd0}}}, {tmp_57_reg_5160}}}, {2'd0}}}, {tmp_58_reg_5167}}}, {2'd0}}}, {tmp_59_reg_5174}}}, {2'd0}}}, {tmp_60_reg_5182}}}, {2'd0}}}, {tmp_61_reg_5190}}}, {2'd0}}}, {tmp_62_reg_5198}}}, {2'd0}}}, {tmp_63_reg_5206}}}, {2'd0}}}, {tmp_64_reg_5214}}}, {2'd0}}}, {tmp_65_reg_5222}}}, {2'd0}}}, {tmp_66_reg_5230}}}, {2'd0}}}, {trunc_ln1348_1_reg_5238}};

assign and_ln1348_3_fu_2129_p32 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_52_fu_1975_p4}, {2'd0}}, {tmp_53_fu_1985_p4}}, {2'd0}}, {tmp_54_fu_1995_p4}}, {2'd0}}, {tmp_55_fu_2005_p4}}, {2'd0}}, {tmp_56_fu_2015_p4}}, {2'd0}}, {tmp_57_fu_2025_p4}}, {2'd0}}, {tmp_58_fu_2035_p4}}, {2'd0}}, {tmp_59_fu_2045_p4}}, {2'd0}}, {tmp_60_fu_2055_p4}}, {2'd0}}, {tmp_61_fu_2065_p4}}, {2'd0}}, {tmp_62_fu_2075_p4}}, {2'd0}}, {tmp_63_fu_2085_p4}}, {2'd0}}, {tmp_64_fu_2095_p4}}, {2'd0}}, {tmp_65_fu_2105_p4}}, {2'd0}}, {tmp_66_fu_2115_p4}}, {2'd0}}, {trunc_ln1348_1_fu_2125_p1}};

assign and_ln1348_4_cast_fu_3201_p31 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{1'd0}, {tmp_68_reg_5247}}}, {2'd0}}}, {tmp_69_reg_5253}}}, {2'd0}}}, {tmp_70_reg_5259}}}, {2'd0}}}, {tmp_71_reg_5266}}}, {2'd0}}}, {tmp_72_reg_5273}}}, {2'd0}}}, {tmp_73_reg_5280}}}, {2'd0}}}, {tmp_74_reg_5287}}}, {2'd0}}}, {tmp_75_reg_5295}}}, {2'd0}}}, {tmp_76_reg_5303}}}, {2'd0}}}, {tmp_77_reg_5311}}}, {2'd0}}}, {tmp_78_reg_5319}}}, {2'd0}}}, {tmp_79_reg_5327}}}, {2'd0}}}, {tmp_80_reg_5335}}}, {2'd0}}}, {tmp_81_reg_5343}}}, {2'd0}}}, {tmp_82_reg_5351}};

assign and_ln1348_4_fu_2359_p32 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_67_fu_2199_p4}, {2'd0}}, {tmp_68_fu_2209_p4}}, {2'd0}}, {tmp_69_fu_2219_p4}}, {2'd0}}, {tmp_70_fu_2229_p4}}, {2'd0}}, {tmp_71_fu_2239_p4}}, {2'd0}}, {tmp_72_fu_2249_p4}}, {2'd0}}, {tmp_73_fu_2259_p4}}, {2'd0}}, {tmp_74_fu_2269_p4}}, {2'd0}}, {tmp_75_fu_2279_p4}}, {2'd0}}, {tmp_76_fu_2289_p4}}, {2'd0}}, {tmp_77_fu_2299_p4}}, {2'd0}}, {tmp_78_fu_2309_p4}}, {2'd0}}, {tmp_79_fu_2319_p4}}, {2'd0}}, {tmp_80_fu_2329_p4}}, {2'd0}}, {tmp_81_fu_2339_p4}}, {2'd0}}, {tmp_82_fu_2349_p4}};

assign and_ln1348_cast_fu_2445_p31 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{1'd0}, {tmp_5_reg_4903}}}, {2'd0}}}, {tmp_6_reg_4909}}}, {2'd0}}}, {tmp_7_reg_4915}}}, {2'd0}}}, {tmp_8_reg_4922}}}, {2'd0}}}, {tmp_9_reg_4929}}}, {2'd0}}}, {tmp_10_reg_4936}}}, {2'd0}}}, {tmp_11_reg_4943}}}, {2'd0}}}, {tmp_12_reg_4951}}}, {2'd0}}}, {tmp_13_reg_4959}}}, {2'd0}}}, {tmp_14_reg_4967}}}, {2'd0}}}, {tmp_15_reg_4975}}}, {2'd0}}}, {tmp_16_reg_4983}}}, {2'd0}}}, {tmp_17_reg_4991}}}, {2'd0}}}, {tmp_18_reg_4999}}}, {2'd0}}}, {trunc_ln1348_reg_5007}};

assign and_ln1348_s_fu_1552_p32 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_s_fu_1398_p4}, {2'd0}}, {tmp_5_fu_1408_p4}}, {2'd0}}, {tmp_6_fu_1418_p4}}, {2'd0}}, {tmp_7_fu_1428_p4}}, {2'd0}}, {tmp_8_fu_1438_p4}}, {2'd0}}, {tmp_9_fu_1448_p4}}, {2'd0}}, {tmp_10_fu_1458_p4}}, {2'd0}}, {tmp_11_fu_1468_p4}}, {2'd0}}, {tmp_12_fu_1478_p4}}, {2'd0}}, {tmp_13_fu_1488_p4}}, {2'd0}}, {tmp_14_fu_1498_p4}}, {2'd0}}, {tmp_15_fu_1508_p4}}, {2'd0}}, {tmp_16_fu_1518_p4}}, {2'd0}}, {tmp_17_fu_1528_p4}}, {2'd0}}, {tmp_18_fu_1538_p4}}, {2'd0}}, {trunc_ln1348_fu_1548_p1}};

assign and_ln1497_2_fu_3641_p15 = {{{{{{{{{{{{{{{{{{{{{{{{{{3'd0}, {tmp_83_fu_3577_p4}}}, {4'd0}}}, {tmp_84_fu_3587_p4}}}, {4'd0}}}, {tmp_85_fu_3597_p4}}}, {4'd0}}}, {tmp_86_fu_3607_p4}}}, {4'd0}}}, {tmp_87_fu_3617_p4}}}, {4'd0}}}, {tmp_88_fu_3627_p4}}}, {4'd0}}}, {trunc_ln1497_2_fu_3637_p1}};

assign and_ln1_fu_2934_p15 = {{{{{{{{{{{{{{{{{{{{{{{{{{3'd0}, {tmp_35_fu_2870_p4}}}, {4'd0}}}, {tmp_36_fu_2880_p4}}}, {4'd0}}}, {tmp_37_fu_2890_p4}}}, {4'd0}}}, {tmp_38_fu_2900_p4}}}, {4'd0}}}, {tmp_39_fu_2910_p4}}}, {4'd0}}}, {tmp_40_fu_2920_p4}}}, {4'd0}}}, {trunc_ln1497_fu_2930_p1}};

assign and_ln2_fu_3859_p11 = {{{{{{{{{{{{{{{{{{3'd0}, {tmp_48_reg_5396}}}, {4'd0}}}, {tmp_49_reg_5401}}}, {4'd0}}}, {tmp_50_reg_5406}}}, {4'd0}}}, {tmp_51_reg_5411}}}, {4'd0}}}, {trunc_ln691_reg_5416}};

assign and_ln608_1_fu_673_p2 = (xor_ln608_fu_668_p2 & d_o_idx);

assign and_ln608_2_fu_686_p2 = (tmp_reg_4487 & d_o_idx);

assign and_ln608_fu_656_p2 = (xor_ln689_reg_4469 & tmp_reg_4487);

assign and_ln691_1_fu_3945_p11 = {{{{{{{{{{{{{{{{{{3'd0}, {tmp_96_reg_5462}}}, {4'd0}}}, {tmp_97_reg_5467}}}, {4'd0}}}, {tmp_98_reg_5472}}}, {4'd0}}}, {tmp_99_reg_5477}}}, {4'd0}}}, {trunc_ln691_10_reg_5482}};

assign and_ln_fu_1291_p64 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_851_reg_4578}, {1'd0}}, {tmp_852_reg_4583}}, {1'd0}}, {tmp_853_reg_4588}}, {1'd0}}, {tmp_854_reg_4593}}, {1'd0}}, {tmp_855_reg_4598}}, {1'd0}}, {tmp_856_reg_4603}}, {1'd0}}, {tmp_857_reg_4608}}, {1'd0}}, {tmp_858_reg_4613}}, {1'd0}}, {tmp_859_reg_4618}}, {1'd0}}, {tmp_860_reg_4623}}, {1'd0}}, {tmp_861_reg_4628}}, {1'd0}}, {tmp_862_reg_4633}}, {1'd0}}, {tmp_863_reg_4638}}, {1'd0}}, {tmp_864_reg_4643}}, {1'd0}}, {tmp_865_reg_4648}}, {1'd0}}, {tmp_866_reg_4653}}, {1'd0}}, {tmp_867_reg_4658}}, {1'd0}}, {tmp_868_reg_4663}}, {1'd0}}, {tmp_869_reg_4668}}, {1'd0}}, {tmp_870_reg_4673}}, {1'd0}}, {tmp_871_reg_4678}}, {1'd0}}, {tmp_872_reg_4683}}, {1'd0}}, {tmp_873_reg_4688}}, {1'd0}}, {tmp_874_reg_4693}}, {1'd0}}, {tmp_875_reg_4698}}, {1'd0}}, {tmp_876_reg_4703}}, {1'd0}}, {tmp_877_reg_4708}}, {1'd0}}, {tmp_878_reg_4713}}, {1'd0}}, {tmp_879_reg_4718}}, {1'd0}}, {tmp_880_reg_4723}}, {1'd0}}, {tmp_881_reg_4728}}, {1'd0}}, {tmp_882_reg_4733}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign best_out_V_1_fu_4339_p4 = {{grp_fu_4404_p3[33:20]}};

assign best_out_V_2_fu_4352_p3 = ((cmp_i_i426_reg_4451[0:0] == 1'b1) ? best_out_V_reg_493 : sext_ln708_fu_4348_p1);

assign best_out_V_3_fu_4369_p3 = ((or_ln1494_1_fu_4364_p2[0:0] == 1'b1) ? best_out_V_2_fu_4352_p3 : best_out_V_reg_493);

assign cmp_i_i426_fu_548_p2 = ((layer_type == 2'd2) ? 1'b1 : 1'b0);

assign conv_i615_fu_747_p1 = ret_s_fu_719_p4;

assign conv_i630_fu_739_p1 = ret_3_fu_729_p4;

assign d_o_idx_read_read_fu_314_p2 = d_o_idx;

assign dmem_V_0_1_d0 = o_word_V_3_reg_5575;

assign dmem_V_1_1_d0 = o_word_V_3_reg_5575;

assign i_V_fu_703_p2 = (i_V_8_reg_517 + 16'd128);

assign icmp_ln1494_fu_4333_p2 = (($signed(sext_ln727_2_fu_4321_p1) > $signed(shl_ln5_fu_4325_p3)) ? 1'b1 : 1'b0);

assign icmp_ln605_fu_579_p2 = ((o_V_1_reg_469 == n_outputs) ? 1'b1 : 1'b0);

assign icmp_ln648_1_fu_4186_p2 = ((kh_off_reg_5517 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln648_2_fu_4191_p2 = ((kh_off_reg_5517 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln648_fu_4181_p2 = ((kh_off_reg_5517 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln870_3_fu_4127_p2 = ((o_V_1_reg_469 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln870_fu_628_p2 = ((layer_type == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln878_fu_698_p2 = ((i_V_8_reg_517 < n_inputs) ? 1'b1 : 1'b0);

assign kh_mem_V_address0 = zext_ln534_11_fu_4122_p1;

assign kh_mem_V_address1 = zext_ln534_10_fu_4099_p1;

assign kh_off_1_fu_4108_p1 = o_V_1_reg_469[0:0];

assign kh_off_fu_4104_p1 = o_V_1_reg_469[1:0];

assign ki_V_2_fu_4232_p3 = ((kh_off_1_reg_5524[0:0] == 1'b1) ? p_Result_1_fu_4171_p4 : p_Result_s_fu_4167_p1);

assign lhs_fu_540_p1 = o_index;

assign lshr_ln_fu_602_p4 = {{ret_fu_592_p2[16:7]}};

assign nc_V_8_fu_4218_p3 = ((or_ln648_fu_4204_p2[0:0] == 1'b1) ? select_ln648_fu_4196_p3 : select_ln648_1_fu_4210_p3);

assign o_V_fu_568_p2 = (o_V_1_reg_469 + 16'd1);

assign o_offset_fu_651_p2 = (trunc_ln1346_2_fu_647_p1 + trunc_ln1346_reg_4459);

assign o_word_V_2_fu_4391_p3 = ((cmp_i_i426_reg_4451[0:0] == 1'b1) ? p_Result_2_fu_4303_p4 : o_word_V_4_reg_4527);

assign o_word_V_3_fu_4397_p3 = ((or_ln1494_1_fu_4364_p2[0:0] == 1'b1) ? o_word_V_2_fu_4391_p3 : o_word_V_4_reg_4527);

assign o_word_V_4_fu_690_p3 = ((and_ln608_2_fu_686_p2[0:0] == 1'b1) ? dmem_V_1_1_q0 : select_ln608_1_fu_678_p3);

assign or_ln1494_1_fu_4364_p2 = (or_ln1494_fu_4359_p2 | cmp_i_i426_reg_4451);

assign or_ln1494_fu_4359_p2 = (icmp_ln870_3_reg_5535 | icmp_ln1494_fu_4333_p2);

assign or_ln648_fu_4204_p2 = (icmp_ln648_2_fu_4191_p2 | icmp_ln648_1_fu_4186_p2);

assign out_V_fu_4312_p4 = {{grp_fu_4404_p3[33:14]}};

assign p_Repl2_s_fu_4226_p2 = (($signed(sum_V_reg_528) < $signed(nc_V_8_fu_4218_p3)) ? 1'b1 : 1'b0);

assign p_Result_1_fu_4171_p4 = {{kh_mem_V_q0[47:32]}};

always @ (*) begin
    p_Result_2_fu_4303_p4 = o_word_V_4_reg_4527;
    p_Result_2_fu_4303_p4[zext_ln545_fu_4297_p1] = |(zext_ln844_fu_4300_p1);
end

assign p_Result_3_fu_633_p3 = {{56'd0}, {prediction_V_3_reg_481}};

assign p_Result_s_fu_4167_p1 = kh_mem_V_q0[15:0];

assign prediction_V_1_fu_4377_p3 = ((cmp_i_i426_reg_4451[0:0] == 1'b1) ? prediction_V_3_reg_481 : prediction_V_reg_4517);

assign prediction_V_2_fu_4383_p3 = ((or_ln1494_1_fu_4364_p2[0:0] == 1'b1) ? prediction_V_1_fu_4377_p3 : prediction_V_3_reg_481);

assign prediction_V_fu_643_p1 = o_V_1_reg_469[7:0];

assign r_V_fu_4243_p3 = {{trunc_ln728_fu_4239_p1}, {10'd0}};

assign ret_12_fu_713_p2 = (phi_mul_reg_505 + zext_ln1346_fu_709_p1);

assign ret_3_fu_729_p4 = {{i_V_8_reg_517[15:7]}};

assign ret_4_fu_4089_p4 = {{o_V_1_reg_469[7:2]}};

assign ret_5_fu_4112_p4 = {{o_V_1_reg_469[6:1]}};

assign ret_fu_592_p2 = (zext_ln215_fu_588_p1 + lhs_reg_4441);

assign ret_s_fu_719_p4 = {{ret_12_fu_713_p2[18:7]}};

assign rhs_4_fu_4286_p3 = {{select_ln870_reg_5555}, {12'd0}};

assign select_ln608_1_fu_678_p3 = ((and_ln608_1_fu_673_p2[0:0] == 1'b1) ? dmem_V_1_0_q0 : select_ln608_fu_660_p3);

assign select_ln608_fu_660_p3 = ((and_ln608_fu_656_p2[0:0] == 1'b1) ? dmem_V_0_1_q0 : dmem_V_0_0_q0);

assign select_ln619_1_fu_1022_p3 = ((d_i_idx[0:0] == 1'b1) ? dmem_V_1_1_q0 : dmem_V_0_1_q0);

assign select_ln619_fu_753_p3 = ((d_i_idx[0:0] == 1'b1) ? dmem_V_1_0_q0 : dmem_V_0_0_q0);

assign select_ln648_1_fu_4210_p3 = ((icmp_ln648_fu_4181_p2[0:0] == 1'b1) ? tmp_918_fu_4143_p1 : tmp_917_fu_4133_p4);

assign select_ln648_fu_4196_p3 = ((icmp_ln648_2_fu_4191_p2[0:0] == 1'b1) ? tmp_920_fu_4157_p4 : tmp_919_fu_4147_p4);

assign select_ln870_fu_4279_p3 = ((kh_off_1_reg_5524[0:0] == 1'b1) ? tmp_103_fu_4259_p4 : tmp_104_fu_4269_p4);

assign sext_ln619_fu_4048_p1 = $signed(sub_ln69_fu_4042_p2);

assign sext_ln691_447_fu_4079_p1 = $signed(add_ln691_537_fu_4073_p2);

assign sext_ln691_fu_4069_p1 = $signed(sub_ln69_1_fu_4063_p2);

assign sext_ln708_fu_4348_p1 = $signed(best_out_V_1_fu_4339_p4);

assign sext_ln727_2_fu_4321_p1 = $signed(out_V_fu_4312_p4);

assign shl_ln1497_1_fu_4052_p3 = {{add_ln1497_3_reg_5502}, {1'd0}};

assign shl_ln5_fu_4325_p3 = {{best_out_V_reg_493}, {6'd0}};

assign shl_ln_fu_4031_p3 = {{add_ln1497_1_reg_5497}, {1'd0}};

assign sub_ln692_1_fu_1970_p2 = (xor_ln1350_1_reg_4738 - zext_ln692_1_fu_1966_p1);

assign sub_ln692_fu_1393_p2 = (xor_ln1350_reg_4573 - zext_ln692_fu_1389_p1);

assign sub_ln69_1_fu_4063_p2 = (9'd64 - zext_ln69_9_fu_4059_p1);

assign sub_ln69_fu_4042_p2 = (9'd64 - zext_ln69_4_fu_4038_p1);

assign tmp_103_fu_4259_p4 = {{kh_mem_V_q0[63:48]}};

assign tmp_104_fu_4269_p4 = {{kh_mem_V_q0[31:16]}};

assign tmp_10_fu_1458_p4 = {{sub_ln692_fu_1393_p2[37:36]}};

assign tmp_11_fu_1468_p4 = {{sub_ln692_fu_1393_p2[33:32]}};

assign tmp_12_fu_1478_p4 = {{sub_ln692_fu_1393_p2[29:28]}};

assign tmp_13_fu_1488_p4 = {{sub_ln692_fu_1393_p2[25:24]}};

assign tmp_14_fu_1498_p4 = {{sub_ln692_fu_1393_p2[21:20]}};

assign tmp_15_fu_1508_p4 = {{sub_ln692_fu_1393_p2[17:16]}};

assign tmp_16_fu_1518_p4 = {{sub_ln692_fu_1393_p2[13:12]}};

assign tmp_17_fu_1528_p4 = {{sub_ln692_fu_1393_p2[9:8]}};

assign tmp_18_fu_1538_p4 = {{sub_ln692_fu_1393_p2[5:4]}};

assign tmp_19_fu_1622_p4 = {{sub_ln692_fu_1393_p2[63:62]}};

assign tmp_20_fu_1632_p4 = {{sub_ln692_fu_1393_p2[59:58]}};

assign tmp_21_fu_1642_p4 = {{sub_ln692_fu_1393_p2[55:54]}};

assign tmp_22_fu_1652_p4 = {{sub_ln692_fu_1393_p2[51:50]}};

assign tmp_23_fu_1662_p4 = {{sub_ln692_fu_1393_p2[47:46]}};

assign tmp_24_fu_1672_p4 = {{sub_ln692_fu_1393_p2[43:42]}};

assign tmp_25_fu_1682_p4 = {{sub_ln692_fu_1393_p2[39:38]}};

assign tmp_26_fu_1692_p4 = {{sub_ln692_fu_1393_p2[35:34]}};

assign tmp_27_fu_1702_p4 = {{sub_ln692_fu_1393_p2[31:30]}};

assign tmp_28_fu_1712_p4 = {{sub_ln692_fu_1393_p2[27:26]}};

assign tmp_29_fu_1722_p4 = {{sub_ln692_fu_1393_p2[23:22]}};

assign tmp_30_fu_1732_p4 = {{sub_ln692_fu_1393_p2[19:18]}};

assign tmp_31_fu_1742_p4 = {{sub_ln692_fu_1393_p2[15:14]}};

assign tmp_32_fu_1752_p4 = {{sub_ln692_fu_1393_p2[11:10]}};

assign tmp_33_fu_1762_p4 = {{sub_ln692_fu_1393_p2[7:6]}};

assign tmp_34_fu_1772_p4 = {{sub_ln692_fu_1393_p2[3:2]}};

assign tmp_35_fu_2870_p4 = {{add_ln69_6_fu_2858_p2[51:48]}};

assign tmp_36_fu_2880_p4 = {{add_ln69_6_fu_2858_p2[43:40]}};

assign tmp_37_fu_2890_p4 = {{add_ln69_6_fu_2858_p2[35:32]}};

assign tmp_38_fu_2900_p4 = {{add_ln69_6_fu_2858_p2[27:24]}};

assign tmp_39_fu_2910_p4 = {{add_ln69_6_fu_2858_p2[19:16]}};

assign tmp_40_fu_2920_p4 = {{add_ln69_6_fu_2858_p2[11:8]}};

assign tmp_41_fu_2966_p4 = {{add_ln69_2_fu_2826_p2[59:56]}};

assign tmp_42_fu_2976_p4 = {{add_ln69_2_fu_2826_p2[51:48]}};

assign tmp_43_fu_2986_p4 = {{add_ln69_2_fu_2826_p2[43:40]}};

assign tmp_44_fu_2996_p4 = {{add_ln69_2_fu_2826_p2[35:32]}};

assign tmp_45_fu_3006_p4 = {{add_ln69_2_fu_2826_p2[27:24]}};

assign tmp_46_fu_3016_p4 = {{add_ln69_2_fu_2826_p2[19:16]}};

assign tmp_47_fu_3026_p4 = {{add_ln69_2_fu_2826_p2[11:8]}};

assign tmp_52_fu_1975_p4 = {{sub_ln692_1_fu_1970_p2[61:60]}};

assign tmp_53_fu_1985_p4 = {{sub_ln692_1_fu_1970_p2[57:56]}};

assign tmp_54_fu_1995_p4 = {{sub_ln692_1_fu_1970_p2[53:52]}};

assign tmp_55_fu_2005_p4 = {{sub_ln692_1_fu_1970_p2[49:48]}};

assign tmp_56_fu_2015_p4 = {{sub_ln692_1_fu_1970_p2[45:44]}};

assign tmp_57_fu_2025_p4 = {{sub_ln692_1_fu_1970_p2[41:40]}};

assign tmp_58_fu_2035_p4 = {{sub_ln692_1_fu_1970_p2[37:36]}};

assign tmp_59_fu_2045_p4 = {{sub_ln692_1_fu_1970_p2[33:32]}};

assign tmp_5_fu_1408_p4 = {{sub_ln692_fu_1393_p2[57:56]}};

assign tmp_60_fu_2055_p4 = {{sub_ln692_1_fu_1970_p2[29:28]}};

assign tmp_61_fu_2065_p4 = {{sub_ln692_1_fu_1970_p2[25:24]}};

assign tmp_62_fu_2075_p4 = {{sub_ln692_1_fu_1970_p2[21:20]}};

assign tmp_63_fu_2085_p4 = {{sub_ln692_1_fu_1970_p2[17:16]}};

assign tmp_64_fu_2095_p4 = {{sub_ln692_1_fu_1970_p2[13:12]}};

assign tmp_65_fu_2105_p4 = {{sub_ln692_1_fu_1970_p2[9:8]}};

assign tmp_66_fu_2115_p4 = {{sub_ln692_1_fu_1970_p2[5:4]}};

assign tmp_67_fu_2199_p4 = {{sub_ln692_1_fu_1970_p2[63:62]}};

assign tmp_68_fu_2209_p4 = {{sub_ln692_1_fu_1970_p2[59:58]}};

assign tmp_69_fu_2219_p4 = {{sub_ln692_1_fu_1970_p2[55:54]}};

assign tmp_6_fu_1418_p4 = {{sub_ln692_fu_1393_p2[53:52]}};

assign tmp_70_fu_2229_p4 = {{sub_ln692_1_fu_1970_p2[51:50]}};

assign tmp_71_fu_2239_p4 = {{sub_ln692_1_fu_1970_p2[47:46]}};

assign tmp_72_fu_2249_p4 = {{sub_ln692_1_fu_1970_p2[43:42]}};

assign tmp_73_fu_2259_p4 = {{sub_ln692_1_fu_1970_p2[39:38]}};

assign tmp_74_fu_2269_p4 = {{sub_ln692_1_fu_1970_p2[35:34]}};

assign tmp_75_fu_2279_p4 = {{sub_ln692_1_fu_1970_p2[31:30]}};

assign tmp_76_fu_2289_p4 = {{sub_ln692_1_fu_1970_p2[27:26]}};

assign tmp_77_fu_2299_p4 = {{sub_ln692_1_fu_1970_p2[23:22]}};

assign tmp_78_fu_2309_p4 = {{sub_ln692_1_fu_1970_p2[19:18]}};

assign tmp_79_fu_2319_p4 = {{sub_ln692_1_fu_1970_p2[15:14]}};

assign tmp_7_fu_1428_p4 = {{sub_ln692_fu_1393_p2[49:48]}};

assign tmp_80_fu_2329_p4 = {{sub_ln692_1_fu_1970_p2[11:10]}};

assign tmp_81_fu_2339_p4 = {{sub_ln692_1_fu_1970_p2[7:6]}};

assign tmp_82_fu_2349_p4 = {{sub_ln692_1_fu_1970_p2[3:2]}};

assign tmp_83_fu_3577_p4 = {{add_ln69_9_fu_3565_p2[51:48]}};

assign tmp_84_fu_3587_p4 = {{add_ln69_9_fu_3565_p2[43:40]}};

assign tmp_85_fu_3597_p4 = {{add_ln69_9_fu_3565_p2[35:32]}};

assign tmp_86_fu_3607_p4 = {{add_ln69_9_fu_3565_p2[27:24]}};

assign tmp_87_fu_3617_p4 = {{add_ln69_9_fu_3565_p2[19:16]}};

assign tmp_88_fu_3627_p4 = {{add_ln69_9_fu_3565_p2[11:8]}};

assign tmp_89_fu_3673_p4 = {{add_ln69_1_fu_3533_p2[59:56]}};

assign tmp_8_fu_1438_p4 = {{sub_ln692_fu_1393_p2[45:44]}};

assign tmp_90_fu_3683_p4 = {{add_ln69_1_fu_3533_p2[51:48]}};

assign tmp_917_fu_4133_p4 = {{kh_mem_V_q1[63:48]}};

assign tmp_918_fu_4143_p1 = kh_mem_V_q1[15:0];

assign tmp_919_fu_4147_p4 = {{kh_mem_V_q1[31:16]}};

assign tmp_91_fu_3693_p4 = {{add_ln69_1_fu_3533_p2[43:40]}};

assign tmp_920_fu_4157_p4 = {{kh_mem_V_q1[47:32]}};

assign tmp_92_fu_3703_p4 = {{add_ln69_1_fu_3533_p2[35:32]}};

assign tmp_93_fu_3713_p4 = {{add_ln69_1_fu_3533_p2[27:24]}};

assign tmp_94_fu_3723_p4 = {{add_ln69_1_fu_3533_p2[19:16]}};

assign tmp_95_fu_3733_p4 = {{add_ln69_1_fu_3533_p2[11:8]}};

assign tmp_9_fu_1448_p4 = {{sub_ln692_fu_1393_p2[41:40]}};

assign tmp_s_fu_1398_p4 = {{sub_ln692_fu_1393_p2[61:60]}};

assign trunc_ln1346_1_fu_558_p1 = o_index[6:0];

assign trunc_ln1346_2_fu_647_p1 = o_V_1_reg_469[5:0];

assign trunc_ln1346_fu_554_p1 = o_index[5:0];

assign trunc_ln1348_1_fu_2125_p1 = sub_ln692_1_fu_1970_p2[1:0];

assign trunc_ln1348_fu_1548_p1 = sub_ln692_fu_1393_p2[1:0];

assign trunc_ln1497_1_fu_4004_p4 = {{add_ln691_536_fu_3999_p2[38:32]}};

assign trunc_ln1497_2_cast_fu_2647_p27 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{2'd0}, {tmp_7_reg_4915}}}, {2'd0}}}, {tmp_8_reg_4922}}}, {2'd0}}}, {tmp_9_reg_4929}}}, {2'd0}}}, {tmp_10_reg_4936}}}, {2'd0}}}, {tmp_11_reg_4943}}}, {2'd0}}}, {tmp_12_reg_4951}}}, {2'd0}}}, {tmp_13_reg_4959}}}, {2'd0}}}, {tmp_14_reg_4967}}}, {2'd0}}}, {tmp_15_reg_4975}}}, {2'd0}}}, {tmp_16_reg_4983}}}, {2'd0}}}, {tmp_17_reg_4991}}}, {2'd0}}}, {tmp_18_reg_4999}}}, {2'd0}}}, {trunc_ln1348_reg_5007}};

assign trunc_ln1497_2_fu_3637_p1 = add_ln69_9_fu_3565_p2[3:0];

assign trunc_ln1497_3_cast_fu_2690_p27 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{2'd0}, {tmp_22_reg_5028}}}, {2'd0}}}, {tmp_23_reg_5035}}}, {2'd0}}}, {tmp_24_reg_5042}}}, {2'd0}}}, {tmp_25_reg_5049}}}, {2'd0}}}, {tmp_26_reg_5056}}}, {2'd0}}}, {tmp_27_reg_5064}}}, {2'd0}}}, {tmp_28_reg_5072}}}, {2'd0}}}, {tmp_29_reg_5080}}}, {2'd0}}}, {tmp_30_reg_5088}}}, {2'd0}}}, {tmp_31_reg_5096}}}, {2'd0}}}, {tmp_32_reg_5104}}}, {2'd0}}}, {tmp_33_reg_5112}}}, {2'd0}}}, {tmp_34_reg_5120}};

assign trunc_ln1497_4_cast_fu_3354_p27 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{2'd0}, {tmp_55_reg_5146}}}, {2'd0}}}, {tmp_56_reg_5153}}}, {2'd0}}}, {tmp_57_reg_5160}}}, {2'd0}}}, {tmp_58_reg_5167}}}, {2'd0}}}, {tmp_59_reg_5174}}}, {2'd0}}}, {tmp_60_reg_5182}}}, {2'd0}}}, {tmp_61_reg_5190}}}, {2'd0}}}, {tmp_62_reg_5198}}}, {2'd0}}}, {tmp_63_reg_5206}}}, {2'd0}}}, {tmp_64_reg_5214}}}, {2'd0}}}, {tmp_65_reg_5222}}}, {2'd0}}}, {tmp_66_reg_5230}}}, {2'd0}}}, {trunc_ln1348_1_reg_5238}};

assign trunc_ln1497_5_cast_fu_3397_p27 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{2'd0}, {tmp_70_reg_5259}}}, {2'd0}}}, {tmp_71_reg_5266}}}, {2'd0}}}, {tmp_72_reg_5273}}}, {2'd0}}}, {tmp_73_reg_5280}}}, {2'd0}}}, {tmp_74_reg_5287}}}, {2'd0}}}, {tmp_75_reg_5295}}}, {2'd0}}}, {tmp_76_reg_5303}}}, {2'd0}}}, {tmp_77_reg_5311}}}, {2'd0}}}, {tmp_78_reg_5319}}}, {2'd0}}}, {tmp_79_reg_5327}}}, {2'd0}}}, {tmp_80_reg_5335}}}, {2'd0}}}, {tmp_81_reg_5343}}}, {2'd0}}}, {tmp_82_reg_5351}};

assign trunc_ln1497_fu_2930_p1 = add_ln69_6_fu_2858_p2[3:0];

assign trunc_ln4_fu_3918_p4 = {{add_ln691_532_fu_3913_p2[38:32]}};

assign trunc_ln691_10_fu_3829_p1 = add_ln1497_8_fu_3571_p2[3:0];

assign trunc_ln691_2_fu_3992_p3 = {{3'd0}, {tmp_95_reg_5451}};

assign trunc_ln691_4_fu_3036_p14 = {{{{{{{{{{{{{tmp_41_fu_2966_p4}, {4'd0}}, {tmp_42_fu_2976_p4}}, {4'd0}}, {tmp_43_fu_2986_p4}}, {4'd0}}, {tmp_44_fu_2996_p4}}, {4'd0}}, {tmp_45_fu_3006_p4}}, {4'd0}}, {tmp_46_fu_3016_p4}}, {4'd0}}, {tmp_47_fu_3026_p4}};

assign trunc_ln691_5_fu_3878_p11 = {{{{{{{{{{{{{{{{{{3'd0}, {tmp_43_reg_5365}}}, {4'd0}}}, {tmp_44_reg_5370}}}, {4'd0}}}, {tmp_45_reg_5375}}}, {4'd0}}}, {tmp_46_reg_5380}}}, {4'd0}}}, {tmp_47_reg_5385}};

assign trunc_ln691_7_fu_3743_p14 = {{{{{{{{{{{{{tmp_89_fu_3673_p4}, {4'd0}}, {tmp_90_fu_3683_p4}}, {4'd0}}, {tmp_91_fu_3693_p4}}, {4'd0}}, {tmp_92_fu_3703_p4}}, {4'd0}}, {tmp_93_fu_3713_p4}}, {4'd0}}, {tmp_94_fu_3723_p4}}, {4'd0}}, {tmp_95_fu_3733_p4}};

assign trunc_ln691_8_fu_3964_p11 = {{{{{{{{{{{{{{{{{{3'd0}, {tmp_91_reg_5431}}}, {4'd0}}}, {tmp_92_reg_5436}}}, {4'd0}}}, {tmp_93_reg_5441}}}, {4'd0}}}, {tmp_94_reg_5446}}}, {4'd0}}}, {tmp_95_reg_5451}};

assign trunc_ln691_fu_3122_p1 = add_ln1497_2_fu_2864_p2[3:0];

assign trunc_ln69_10_cast_fu_2816_p4 = {{add_ln69_10_fu_2641_p2[55:4]}};

assign trunc_ln69_11_cast_fu_2848_p4 = {{add_ln69_10_fu_2641_p2[39:4]}};

assign trunc_ln69_15_cast_fu_3455_p19 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{2'd0}, {tmp_59_reg_5174}}}, {2'd0}}}, {tmp_60_reg_5182}}}, {2'd0}}}, {tmp_61_reg_5190}}}, {2'd0}}}, {tmp_62_reg_5198}}}, {2'd0}}}, {tmp_63_reg_5206}}}, {2'd0}}}, {tmp_64_reg_5214}}}, {2'd0}}}, {tmp_65_reg_5222}}}, {2'd0}}}, {tmp_66_reg_5230}}}, {2'd0}}}, {trunc_ln1348_1_reg_5238}};

assign trunc_ln69_16_cast_fu_3486_p19 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{2'd0}, {tmp_74_reg_5287}}}, {2'd0}}}, {tmp_75_reg_5295}}}, {2'd0}}}, {tmp_76_reg_5303}}}, {2'd0}}}, {tmp_77_reg_5311}}}, {2'd0}}}, {tmp_78_reg_5319}}}, {2'd0}}}, {tmp_79_reg_5327}}}, {2'd0}}}, {tmp_80_reg_5335}}}, {2'd0}}}, {tmp_81_reg_5343}}}, {2'd0}}}, {tmp_82_reg_5351}};

assign trunc_ln69_17_cast_fu_3523_p4 = {{add_ln69_11_fu_3348_p2[55:4]}};

assign trunc_ln69_18_cast_fu_3555_p4 = {{add_ln69_11_fu_3348_p2[39:4]}};

assign trunc_ln69_1_fu_3299_p31 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{2'd0}, {tmp_68_reg_5247}}}, {2'd0}}}, {tmp_69_reg_5253}}}, {2'd0}}}, {tmp_70_reg_5259}}}, {2'd0}}}, {tmp_71_reg_5266}}}, {2'd0}}}, {tmp_72_reg_5273}}}, {2'd0}}}, {tmp_73_reg_5280}}}, {2'd0}}}, {tmp_74_reg_5287}}}, {2'd0}}}, {tmp_75_reg_5295}}}, {2'd0}}}, {tmp_76_reg_5303}}}, {2'd0}}}, {tmp_77_reg_5311}}}, {2'd0}}}, {tmp_78_reg_5319}}}, {2'd0}}}, {tmp_79_reg_5327}}}, {2'd0}}}, {tmp_80_reg_5335}}}, {2'd0}}}, {tmp_81_reg_5343}}}, {2'd0}}}, {tmp_82_reg_5351}};

assign trunc_ln69_2_fu_2832_p4 = {{add_ln69_10_fu_2641_p2[7:4]}};

assign trunc_ln69_5_fu_3539_p4 = {{add_ln69_11_fu_3348_p2[7:4]}};

assign trunc_ln69_6_fu_2543_p31 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{2'd0}, {tmp_5_reg_4903}}}, {2'd0}}}, {tmp_6_reg_4909}}}, {2'd0}}}, {tmp_7_reg_4915}}}, {2'd0}}}, {tmp_8_reg_4922}}}, {2'd0}}}, {tmp_9_reg_4929}}}, {2'd0}}}, {tmp_10_reg_4936}}}, {2'd0}}}, {tmp_11_reg_4943}}}, {2'd0}}}, {tmp_12_reg_4951}}}, {2'd0}}}, {tmp_13_reg_4959}}}, {2'd0}}}, {tmp_14_reg_4967}}}, {2'd0}}}, {tmp_15_reg_4975}}}, {2'd0}}}, {tmp_16_reg_4983}}}, {2'd0}}}, {tmp_17_reg_4991}}}, {2'd0}}}, {tmp_18_reg_4999}}}, {2'd0}}}, {trunc_ln1348_reg_5007}};

assign trunc_ln69_7_fu_2592_p31 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{2'd0}, {tmp_20_reg_5016}}}, {2'd0}}}, {tmp_21_reg_5022}}}, {2'd0}}}, {tmp_22_reg_5028}}}, {2'd0}}}, {tmp_23_reg_5035}}}, {2'd0}}}, {tmp_24_reg_5042}}}, {2'd0}}}, {tmp_25_reg_5049}}}, {2'd0}}}, {tmp_26_reg_5056}}}, {2'd0}}}, {tmp_27_reg_5064}}}, {2'd0}}}, {tmp_28_reg_5072}}}, {2'd0}}}, {tmp_29_reg_5080}}}, {2'd0}}}, {tmp_30_reg_5088}}}, {2'd0}}}, {tmp_31_reg_5096}}}, {2'd0}}}, {tmp_32_reg_5104}}}, {2'd0}}}, {tmp_33_reg_5112}}}, {2'd0}}}, {tmp_34_reg_5120}};

assign trunc_ln69_9_cast_fu_2748_p19 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{2'd0}, {tmp_11_reg_4943}}}, {2'd0}}}, {tmp_12_reg_4951}}}, {2'd0}}}, {tmp_13_reg_4959}}}, {2'd0}}}, {tmp_14_reg_4967}}}, {2'd0}}}, {tmp_15_reg_4975}}}, {2'd0}}}, {tmp_16_reg_4983}}}, {2'd0}}}, {tmp_17_reg_4991}}}, {2'd0}}}, {tmp_18_reg_4999}}}, {2'd0}}}, {trunc_ln1348_reg_5007}};

assign trunc_ln69_cast_fu_2779_p19 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{2'd0}, {tmp_26_reg_5056}}}, {2'd0}}}, {tmp_27_reg_5064}}}, {2'd0}}}, {tmp_28_reg_5072}}}, {2'd0}}}, {tmp_29_reg_5080}}}, {2'd0}}}, {tmp_30_reg_5088}}}, {2'd0}}}, {tmp_31_reg_5096}}}, {2'd0}}}, {tmp_32_reg_5104}}}, {2'd0}}}, {tmp_33_reg_5112}}}, {2'd0}}}, {tmp_34_reg_5120}};

assign trunc_ln69_s_fu_3250_p31 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{2'd0}, {tmp_53_reg_5134}}}, {2'd0}}}, {tmp_54_reg_5140}}}, {2'd0}}}, {tmp_55_reg_5146}}}, {2'd0}}}, {tmp_56_reg_5153}}}, {2'd0}}}, {tmp_57_reg_5160}}}, {2'd0}}}, {tmp_58_reg_5167}}}, {2'd0}}}, {tmp_59_reg_5174}}}, {2'd0}}}, {tmp_60_reg_5182}}}, {2'd0}}}, {tmp_61_reg_5190}}}, {2'd0}}}, {tmp_62_reg_5198}}}, {2'd0}}}, {tmp_63_reg_5206}}}, {2'd0}}}, {tmp_64_reg_5214}}}, {2'd0}}}, {tmp_65_reg_5222}}}, {2'd0}}}, {tmp_66_reg_5230}}}, {2'd0}}}, {trunc_ln1348_1_reg_5238}};

assign trunc_ln728_fu_4239_p1 = sum_V_reg_528[9:0];

assign trunc_ln878_fu_584_p1 = o_V_1_reg_469[6:0];

assign trunc_ln_fu_3906_p3 = {{3'd0}, {tmp_47_reg_5385}};

assign wt_mem_V_0_address0 = conv_i615_fu_747_p1;

assign wt_mem_V_1_address0 = conv_i615_fu_747_p1;

assign xor_ln1350_1_fu_1029_p2 = (wt_mem_V_1_q0 ^ select_ln619_1_fu_1022_p3);

assign xor_ln1350_fu_760_p2 = (wt_mem_V_0_q0 ^ select_ln619_fu_753_p3);

assign xor_ln608_fu_668_p2 = (tmp_reg_4487 ^ 1'd1);

assign xor_ln689_fu_562_p2 = (d_o_idx ^ 1'd1);

assign zext_ln1346_fu_709_p1 = i_V_8_reg_517;

assign zext_ln1497_1_fu_2195_p1 = and_ln1348_3_fu_2129_p32;

assign zext_ln1497_fu_1618_p1 = and_ln1348_s_fu_1552_p32;

assign zext_ln215_fu_588_p1 = o_V_1_reg_469;

assign zext_ln534_10_fu_4099_p1 = ret_4_fu_4089_p4;

assign zext_ln534_11_fu_4122_p1 = ret_5_fu_4112_p4;

assign zext_ln534_fu_612_p1 = lshr_ln_fu_602_p4;

assign zext_ln545_fu_4297_p1 = o_offset_reg_4522;

assign zext_ln613_fu_544_p1 = n_inputs;

assign zext_ln691_1_fu_3903_p1 = add_ln691_reg_5391;

assign zext_ln691_2_fu_3773_p1 = trunc_ln691_7_fu_3743_p14;

assign zext_ln691_3_fu_3989_p1 = add_ln691_534_reg_5457;

assign zext_ln691_fu_3066_p1 = trunc_ln691_4_fu_3036_p14;

assign zext_ln692_1_fu_1966_p1 = and_ln1348_2_fu_1868_p64;

assign zext_ln692_fu_1389_p1 = and_ln_fu_1291_p64;

assign zext_ln69_1_fu_2739_p1 = trunc_ln69_8_reg_5129;

assign zext_ln69_2_fu_2742_p1 = trunc_ln1348_reg_5007;

assign zext_ln69_3_fu_2745_p1 = tmp_34_reg_5120;

assign zext_ln69_4_fu_4038_p1 = shl_ln_fu_4031_p3;

assign zext_ln69_5_fu_2425_p1 = and_ln1348_4_fu_2359_p32;

assign zext_ln69_6_fu_3446_p1 = trunc_ln69_3_reg_5360;

assign zext_ln69_7_fu_3449_p1 = trunc_ln1348_1_reg_5238;

assign zext_ln69_8_fu_3452_p1 = tmp_82_reg_5351;

assign zext_ln69_9_fu_4059_p1 = shl_ln1497_1_fu_4052_p3;

assign zext_ln69_fu_1848_p1 = and_ln1348_1_fu_1782_p32;

assign zext_ln844_fu_4300_p1 = p_Repl2_s_reg_5540;

always @ (posedge ap_clk) begin
    lhs_reg_4441[16] <= 1'b0;
    zext_ln613_reg_4446[18:16] <= 3'b000;
end

endmodule //top_bin_dense
