+incdir+${HLS_DESIGN_ROOT}
+incdir+${HLS_DESIGN_ROOT}/hdl/verilog
${HLS_DESIGN_ROOT}/hdl/verilog/calc_0_buffer1.v
${HLS_DESIGN_ROOT}/hdl/verilog/calc_0_control_s_axi.v
${HLS_DESIGN_ROOT}/hdl/verilog/calc_0_fadd_32ns_32ns_32_7_full_dsp_1.v
${HLS_DESIGN_ROOT}/hdl/verilog/calc_0_fmul_32ns_32ns_32_4_max_dsp_1.v
${HLS_DESIGN_ROOT}/hdl/verilog/calc_0_gmem_m_axi.v
${HLS_DESIGN_ROOT}/hdl/verilog/calc_0.v
${HLS_DESIGN_ROOT}/hdl/ip/calc_0_ap_fadd_5_full_dsp_32.v
${HLS_DESIGN_ROOT}/hdl/ip/calc_0_ap_fmul_2_max_dsp_32.v
