stages:
    - build
    - test

variables:
  SCHEDULER_PARAMETERS: "-A pc2-mitarbeiter -p short"

default:
  tags:
    - jacamar
  before_script:
    - module load intelFPGA_pro/21.2.0 bittware_520n/20.4.0_max toolchain/foss/2021a devel/CMake/3.20.1-GCCcore-10.3.0

###
#
# Build all benchmarks
#
###

build:STREAM:
  stage: build
  script:
    - rm -rf build
    - mkdir -p build
    - cd build
    - cmake ../STREAM -DDEFAULT_PLATFORM=0 -DDEFAULT_DEVICE=0
    - make -j 40 all
  artifacts:
    paths:
      - build/bin/stream_kernels_single_emulate.aocx
      - build/bin/stream_kernels_emulate.aocx
      - build/bin/STREAM_FPGA_intel
      - build/bin/STREAM_FPGA_test_intel
  only:
    changes:
      - STREAM/**/*
      - shared/**/*
      - scripts/**/*
      - cmake/**/*
      - .gitlab-ci.yml

build:STREAM_HP:
  stage: build
  script:
    - rm -rf build
    - mkdir -p build
    - cd build
    - cmake ../STREAM -DDATA_TYPE=half -DVECTOR_COUNT=1 -DGLOBAL_MEM_UNROLL=32 -DDEFAULT_PLATFORM=0 -DDEFAULT_DEVICE=0
    - make -j 40 all
  artifacts:
    paths:
      - build/bin/stream_kernels_single_emulate.aocx
      - build/bin/stream_kernels_emulate.aocx
      - build/bin/STREAM_FPGA_intel
      - build/bin/STREAM_FPGA_test_intel
  only:
    changes:
      - STREAM/**/*
      - shared/**/*
      - scripts/**/*
      - cmake/**/*
      - .gitlab-ci.yml

build:STREAM_DP:
  stage: build
  script:
    - rm -rf build
    - mkdir -p build
    - cd build
    - cmake ../STREAM -DDATA_TYPE=double -DVECTOR_COUNT=1 -DGLOBAL_MEM_UNROLL=8 -DDEFAULT_PLATFORM=0 -DDEFAULT_DEVICE=0
    - make -j 40 all
  artifacts:
    paths:
      - build/bin/stream_kernels_single_emulate.aocx
      - build/bin/stream_kernels_emulate.aocx
      - build/bin/STREAM_FPGA_intel
      - build/bin/STREAM_FPGA_test_intel
  only:
    changes:
      - STREAM/**/*
      - shared/**/*
      - scripts/**/*
      - cmake/**/*
      - .gitlab-ci.yml
      
build:RandomAccess:
  stage: build
  script:
    - rm -rf build
    - mkdir -p build
    - cd build
    - cmake ../RandomAccess -DDEFAULT_PLATFORM=0 -DDEFAULT_DEVICE=0
    - make -j 40 all
  artifacts:
    paths:
      - build/bin/random_access_kernels_single_emulate.aocx
      - build/bin/RandomAccess_intel
      - build/bin/RandomAccess_test_intel
  only:
    changes:
      - RandomAccess/**/*
      - shared/**/*
      - scripts/**/*
      - cmake/**/*
      - .gitlab-ci.yml


build:PTRANS:
  stage: build
  script:
    - rm -rf build
    - mkdir -p build
    - cd build
    - cmake ../PTRANS -DDEFAULT_PLATFORM=0 -DDEFAULT_DEVICE=0 -DHOST_EMULATION_REORDER=Yes
    - make -j 40 all
  artifacts:
    paths:
      - build/bin/transpose_DIAG_IEC_emulate.aocx
      - build/bin/transpose_PQ_IEC_emulate.aocx
      - build/bin/transpose_PQ_PCIE_emulate.aocx
      - build/bin/transpose_DIAG_PCIE_emulate.aocx
      - build/bin/transpose_c2_DIAG_IEC_emulate.aocx
      - build/bin/Transpose_intel
      - build/bin/Transpose_test_intel
  only:
    changes:
      - PTRANS/**/*
      - shared/**/*
      - scripts/**/*
      - cmake/**/*
      - .gitlab-ci.yml

build:LINPACK:
  stage: build
  script:
    - rm -rf build
    - mkdir -p build
    - cd build
    - cmake ../LINPACK -DDEFAULT_PLATFORM=0 -DDEFAULT_DEVICE=0 -DLOCAL_MEM_BLOCK_LOG=4 -DREGISTER_BLOCK_LOG=3 -DNUM_REPLICATIONS=3 -DUSE_PCIE_MPI_COMMUNICATION=Yes
    - make -j 40 all
  artifacts:
    paths:
      - build/bin/hpl_torus_PCIE_emulate.aocx
      - build/bin/hpl_torus_IEC_emulate.aocx
      - build/bin/Linpack_intel
      - build/bin/Linpack_test_intel
  only:
    changes:
      - LINPACK/**/*
      - shared/**/*
      - scripts/**/*
      - cmake/**/*
      - .gitlab-ci.yml


build:LINPACK_DP:
  stage: build
  script:
    - rm -rf build
    - mkdir -p build
    - cd build
    - cmake ../LINPACK -DDEFAULT_PLATFORM=0 -DDEFAULT_DEVICE=0 -DLOCAL_MEM_BLOCK_LOG=4 -DREGISTER_BLOCK_LOG=3 -DNUM_REPLICATIONS=3 -DDATA_TYPE=double
    - make -j 40 all
  artifacts:
    paths:
      - build/bin/hpl_torus_PCIE_emulate.aocx
      - build/bin/hpl_torus_IEC_emulate.aocx
      - build/bin/Linpack_intel
      - build/bin/Linpack_test_intel
  only:
    changes:
      - LINPACK/**/*
      - shared/**/*
      - scripts/**/*
      - cmake/**/*

build:GEMM:
  stage: build
  script:
    - rm -rf build
    - mkdir -p build
    - cd build
    - cmake ../GEMM -DDEFAULT_PLATFORM=0 -DDEFAULT_DEVICE=0 -DBLOCK_SIZE=32
    - make -j 40 all
  artifacts:
    paths:
      - build/bin/gemm_base_emulate.aocx
      - build/bin/GEMM_intel
      - build/bin/GEMM_test_intel
  only:
    changes:
      - GEMM/**/*
      - shared/**/*
      - scripts/**/*
      - cmake/**/*
      - .gitlab-ci.yml

build:GEMM_HP_REP2:
  stage: build
  script:
    - rm -rf build
    - mkdir -p build
    - cd build
    - cmake ../GEMM -DDATA_TYPE=half -DNUM_REPLICATIONS=2 -DDEFAULT_PLATFORM=0 -DDEFAULT_DEVICE=0 -DBLOCK_SIZE=32
    - make -j 40 all
  artifacts:
    paths:
      - build/bin/gemm_base_emulate.aocx
      - build/bin/GEMM_intel
      - build/bin/GEMM_test_intel
  only:
    changes:
      - GEMM/**/*
      - shared/**/*
      - scripts/**/*
      - cmake/**/*
      - .gitlab-ci.yml

build:GEMM_DP_REP2:
  stage: build
  script:
    - rm -rf build
    - mkdir -p build
    - cd build
    - cmake ../GEMM -DDATA_TYPE=double -DNUM_REPLICATIONS=2 -DDEFAULT_PLATFORM=0 -DDEFAULT_DEVICE=0 -DBLOCK_SIZE=32
    - make -j 40 all
  artifacts:
    paths:
      - build/bin/gemm_base_emulate.aocx
      - build/bin/GEMM_intel
      - build/bin/GEMM_test_intel
  only:
    changes:
      - GEMM/**/*
      - shared/**/*
      - scripts/**/*
      - cmake/**/*
      - .gitlab-ci.yml

build:FFT:
  stage: build
  script:
    - rm -rf build
    - mkdir -p build
    - cd build
    - cmake ../FFT -DDEFAULT_PLATFORM=0 -DDEFAULT_DEVICE=0
    - make -j 40 all
  artifacts:
    paths:
      - build/bin/fft1d_float_8_emulate.aocx
      - build/bin/FFT_intel
      - build/bin/FFT_test_intel
  only:
    changes:
      - FFT/**/*
      - shared/**/*
      - scripts/**/*
      - cmake/**/*
      - .gitlab-ci.yml

build:FFT_small:
  stage: build
  script:
    - rm -rf build
    - mkdir -p build
    - cd build
    - cmake ../FFT -DDEFAULT_PLATFORM=0 -DDEFAULT_DEVICE=0 -DLOG_FFT_SIZE=4 -DNUM_REPLICATIONS=2
    - make -j 40 all
  artifacts:
    paths:
      - build/bin/fft1d_float_8_emulate.aocx
      - build/bin/FFT_intel
      - build/bin/FFT_test_intel
  only:
    changes:
      - FFT/**/*
      - shared/**/*
      - scripts/**/*
      - cmake/**/*
      - .gitlab-ci.yml

build:b_eff:
  stage: build
  script:
    - rm -rf build
    - mkdir -p build
    - cd build
    - cmake ../b_eff -DDEFAULT_PLATFORM=0 -DDEFAULT_DEVICE=0 -DHOST_EMULATION_REORDER=Yes
    - make -j 40 all
  artifacts:
    paths:
      - build/bin/*
  only:
    changes:
      - b_eff/**/*
      - shared/**/*
      - scripts/**/*
      - cmake/**/*
      - .gitlab-ci.yml

###
#
# Execute tests for all benchmarks
#
###

test:STREAM:
  stage: test
  script:
    - cd build
    - cmake ../STREAM -DDEFAULT_PLATFORM=0 -DDEFAULT_DEVICE=0
    - make CTEST_OUTPUT_ON_FAILURE=1 test
  dependencies:
    - build:STREAM
  artifacts:
    when: on_failure
    paths:
      - build/Testing/Temporary/LastTest.log
  only:
    changes:
      - STREAM/**/*
      - shared/**/*
      - scripts/**/*
      - cmake/**/*
      - .gitlab-ci.yml
  needs: ["build:STREAM"]

test:STREAM_HP:
  stage: test
  script:
    - cd build
    - cmake ../STREAM -DDATA_TYPE=half -DVECTOR_COUNT=1 -DGLOBAL_MEM_UNROLL=32 -DDEFAULT_PLATFORM=0 -DDEFAULT_DEVICE=0
    - make CTEST_OUTPUT_ON_FAILURE=1 test
  dependencies:
    - build:STREAM_HP
  artifacts:
    when: on_failure
    paths:
      - build/Testing/Temporary/LastTest.log
  only:
    changes:
      - STREAM/**/*
      - shared/**/*
      - scripts/**/*
      - cmake/**/*
      - .gitlab-ci.yml
  needs: ["build:STREAM_HP"]
  # Allow failure because: The intel emulator does not seem to support half precision kernel arguments (CL_INVALID_ARG_SIZE)
  allow_failure: true

test:STREAM_DP:
  stage: test
  script:
    - cd build
    - cmake ../STREAM -DDATA_TYPE=double -DVECTOR_COUNT=1 -DGLOBAL_MEM_UNROLL=8 -DDEFAULT_PLATFORM=0 -DDEFAULT_DEVICE=0
    - make CTEST_OUTPUT_ON_FAILURE=1 test
  dependencies:
    - build:STREAM_DP
  artifacts:
    when: on_failure
    paths:
      - build/Testing/Temporary/LastTest.log
  only:
    changes:
      - STREAM/**/*
      - shared/**/*
      - scripts/**/*
      - cmake/**/*
      - .gitlab-ci.yml
  needs: ["build:STREAM_DP"]
    
test:RandomAccess:
  stage: test
  script:
    - cd build
    - cmake ../RandomAccess -DDEFAULT_PLATFORM=0 -DDEFAULT_DEVICE=0
    - make CTEST_OUTPUT_ON_FAILURE=1 test
  dependencies:
    - build:RandomAccess
  artifacts:
    when: on_failure
    paths:
      - build/Testing/Temporary/LastTest.log
  only:
    changes:
      - RandomAccess/**/*
      - shared/**/*
      - scripts/**/*
      - cmake/**/*
      - .gitlab-ci.yml
  needs: ["build:RandomAccess"]

test:PTRANS:
  stage: test
  script:
    - cd build
    - cmake ../PTRANS -DDEFAULT_PLATFORM=0 -DDEFAULT_DEVICE=0 -DPTRANS_HOST_EMULATION_REORDER=Yes
    - cd bin
    - touch kernel_output_ch0
    - touch kernel_output_ch1
    - touch kernel_output_ch2
    - touch kernel_output_ch3
    - ln -s kernel_output_ch0 kernel_input_ch1
    - ln -s kernel_output_ch2 kernel_input_ch3
    - ln -s kernel_output_ch1 kernel_input_ch0
    - ln -s kernel_output_ch3 kernel_input_ch2
    - cd ..
    - make CTEST_OUTPUT_ON_FAILURE=1 test
  dependencies:
    - build:PTRANS
  artifacts:
    when: on_failure
    paths:
      - build/Testing/Temporary/LastTest.log
  only:
    changes:
      - PTRANS/**/*
      - shared/**/*
      - scripts/**/*
      - cmake/**/*
      - .gitlab-ci.yml
  needs: ["build:PTRANS"]

test:LINPACK:
  stage: test
  script:
    - cd build
    - cmake ../LINPACK -DDEFAULT_PLATFORM=0 -DDEFAULT_DEVICE=0  -DLOCAL_MEM_BLOCK_LOG=4 -DREGISTER_BLOCK_LOG=3 -DNUM_REPLICATIONS=3
    - make CTEST_OUTPUT_ON_FAILURE=1 test
  dependencies:
    - build:LINPACK
  artifacts:
    when: on_failure
    paths:
      - build/Testing/Temporary/LastTest.log
  only:
    changes:
      - LINPACK/**/*
      - shared/**/*
      - scripts/**/*
      - cmake/**/*
      - .gitlab-ci.yml
  needs: ["build:LINPACK"]

test:LINPACK_DP:
  stage: test
  script:
    - cd build
    - cmake ../LINPACK -DDEFAULT_PLATFORM=0 -DDEFAULT_DEVICE=0  -DLOCAL_MEM_BLOCK_LOG=4 -DREGISTER_BLOCK_LOG=3 -DNUM_REPLICATIONS=3 -DDATA_TYPE=double
    - make CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 CTEST_OUTPUT_ON_FAILURE=1 test
  dependencies:
    - build:LINPACK_DP
  artifacts:
    when: on_failure
    paths:
      - build/Testing/Temporary/LastTest.log
  only:
    changes:
      - LINPACK/**/*
      - shared/**/*
      - scripts/**/*
      - cmake/**/*
  needs: ["build:LINPACK_DP"]

test:GEMM:
  stage: test
  script:
    - cd build
    - cmake ../GEMM -DDEFAULT_PLATFORM=0 -DDEFAULT_DEVICE=0 -DBLOCK_SIZE=32
    - make CTEST_OUTPUT_ON_FAILURE=1 test
  dependencies:
    - build:GEMM
  artifacts:
    when: on_failure
    paths:
      - build/Testing/Temporary/LastTest.log
  only:
    changes:
      - GEMM/**/*
      - shared/**/*
      - scripts/**/*
      - cmake/**/*
      - .gitlab-ci.yml
  needs: ["build:GEMM"]

test:GEMM_HP_REP2:
  stage: test
  script:
    - cd build
    - cmake ../GEMM -DNUM_REPLICATIONS=2 -DATA_TYPE=half -DDEFAULT_PLATFORM=0 -DDEFAULT_DEVICE=0 -DBLOCK_SIZE=32
    - make CTEST_OUTPUT_ON_FAILURE=1 test
  dependencies:
    - build:GEMM_HP_REP2
  artifacts:
    when: on_failure
    paths:
      - build/Testing/Temporary/LastTest.log
  only:
    changes:
      - GEMM/**/*
      - shared/**/*
      - scripts/**/*
      - cmake/**/*
      - .gitlab-ci.yml
  needs: ["build:GEMM_HP_REP2"]
  # Allow failure because: The intel emulator does not seem to support half precision kernel arguments (CL_INVALID_ARG_SIZE)
  allow_failure: true

test:GEMM_DP_REP2:
  stage: test
  script:
    - cd build
    - cmake ../GEMM -DNUM_REPLICATIONS=2 -DATA_TYPE=double -DDEFAULT_PLATFORM=0 -DDEFAULT_DEVICE=0 -DBLOCK_SIZE=32
    - make CTEST_OUTPUT_ON_FAILURE=1 test
  dependencies:
    - build:GEMM_DP_REP2
  artifacts:
    when: on_failure
    paths:
      - build/Testing/Temporary/LastTest.log
  only:
    changes:
      - GEMM/**/*
      - shared/**/*
      - scripts/**/*
      - cmake/**/*
      - .gitlab-ci.yml
  needs: ["build:GEMM_DP_REP2"]

test:FFT:
  stage: test
  script:
    - cd build
    - cmake ../FFT -DDEFAULT_PLATFORM=0 -DDEFAULT_DEVICE=0
    - make CTEST_OUTPUT_ON_FAILURE=1 test
  dependencies:
    - build:FFT
  artifacts:
    when: on_failure
    paths:
      - build/Testing/Temporary/LastTest.log
  only:
    changes:
      - FFT/**/*
      - shared/**/*
      - scripts/**/*
      - cmake/**/*
      - .gitlab-ci.yml
  needs: ["build:FFT"]

test:FFT_small:
  stage: test
  script:
    - cd build
    - cmake ../FFT -DDEFAULT_PLATFORM=0 -DDEFAULT_DEVICE=0 -DLOG_FFT_SIZE=4 -DNUM_REPLICATIONS=2
    - make CTEST_OUTPUT_ON_FAILURE=1 test
  dependencies:
    - build:FFT_small
  artifacts:
    when: on_failure
    paths:
      - build/Testing/Temporary/LastTest.log
  only:
    changes:
      - FFT/**/*
      - shared/**/*
      - scripts/**/*
      - cmake/**/*
      - .gitlab-ci.yml
  needs: ["build:FFT_small"]

test:b_eff:
  stage: test
  script:
    - cd build
    - cmake ../b_eff -DDEFAULT_PLATFORM=0 -DDEFAULT_DEVICE=0 -DHOST_EMULATION_REORDER=Yes
    - cd bin
    - touch kernel_output_ch0
    - touch kernel_output_ch1
    - touch kernel_output_ch2
    - touch kernel_output_ch3
    - ln -s kernel_output_ch0 kernel_input_ch1
    - ln -s kernel_output_ch2 kernel_input_ch3
    - ln -s kernel_output_ch1 kernel_input_ch0
    - ln -s kernel_output_ch3 kernel_input_ch2
    - cd ..
    - make CTEST_OUTPUT_ON_FAILURE=1 test
  dependencies:
    - build:b_eff
  artifacts:
    when: on_failure
    paths:
      - build/Testing/Temporary/LastTest.log
  only:
    changes:
      - b_eff/**/*
      - shared/**/*
      - scripts/**/*
      - cmake/**/*
      - .gitlab-ci.yml
  needs: ["build:b_eff"]


